#!/usr/bin/python3
#
# Copyright (C) 2021 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; If not, see <http://www.gnu.org/licenses/>.

import os
import sys

# import Cockpit's machinery for test VMs and its browser test API
TEST_DIR = os.path.dirname(__file__)
sys.path.append(os.path.join(TEST_DIR, "common"))
sys.path.append(os.path.join(os.path.dirname(TEST_DIR), "bots/machine"))

from testlib import MachineCase, nondestructive, test_main  # pylint: disable=import-error

@nondestructive
class TestLanguage(MachineCase):

    def testLanguageSwitching(self):
        b = self.browser

        b.open("/cockpit/@localhost/anaconda-webui/index.html")

        # Expect the default language - this is en at this point - adjust the test when better guess is implemented
        b.wait_in_text("button.pf-m-link", "Quit")

        b.wait_in_text("#de", "German (Deutsch)")
        b.click("#de > button")
        b.wait_in_text("#de_DE", "Deutsch (Deutschland)")
        b.click("#de_DE > button")

        b.click("#continue-btn")

        b.expect_load()
        if b.cdp.browser.name == "chromium":
            # HACK: work around language switching in Chrome not working in current session (issue #8160)
            b.reload(ignore_cache=True)

        b.wait_in_text("#user-account", "Benutzererstellung")

        # TODO: Add checks for translated plurals

if __name__ == '__main__':
    test_main()
