#!/usr/bin/python3
#
# Copyright (C) 2022 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; If not, see <http://www.gnu.org/licenses/>.

import anacondalib

from installer import Installer
from storage import Storage
from testlib import test_main  # pylint: disable=import-error


class TestInstallationProgress(anacondalib.VirtInstallMachineCase):

    def testBasic(self):
        # HACK Ignore some selinux errors
        self.allow_journal_messages(".*denied.*comm=\"tar\" name=\"/\".*")

        b = self.browser
        i = Installer(b, self.machine)
        s = Storage(b, self.machine)

        i.open()

        i.reach(i.steps.REVIEW)
        i.begin_installation()

        # the warning can take longer to show up than the regular wait_in_text() timeout
        with b.wait_timeout(600):
            b.wait_in_text("h2", "Successfully installed")

        # Pixel test the complete progress step
        b.assert_pixels(
            "#app",
            "installation-progress-complete",
            ignore=["#betanag-icon"],
            wait_animations=False,
        )

if __name__ == '__main__':
    test_main()
