#!/usr/bin/python3
#
# Copyright (C) 2022 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; If not, see <http://www.gnu.org/licenses/>.

import anacondalib

from installer import Installer
from users import Users, CREATE_ACCOUNT_ID_PREFIX, create_user
from testlib import nondestructive, test_main  # pylint: disable=import-error

@nondestructive
class TestUsers(anacondalib.VirtInstallMachineCase):
    def setUp(self):
        super().setUp()

    def testBasic(self):
        b = self.browser
        i = Installer(b, self.machine)
        u = Users(b, self.machine)

        i.open()

        i.reach(i.steps.ACCOUNTS)
        create_user(b, self.machine)
        b.assert_pixels(
            "#app",
            "users-step-basic",
            ignore=["#betanag-icon"],
        )
        i.reach(i.steps.REVIEW)

        users = u.dbus_get_users()
        self.assertIn('"groups" as 1 "wheel"', users)
        self.assertIn('"is-crypted" b false', users)
        self.assertIn('"password" s "password"', users)

if __name__ == '__main__':
    test_main()
