#!/usr/bin/python3
#
# Copyright (C) 2021 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; If not, see <http://www.gnu.org/licenses/>.

import os
import sys

# import Cockpit's machinery for test VMs and its browser test API
TEST_DIR = os.path.dirname(__file__)
sys.path.append(os.path.join(TEST_DIR, "common"))
sys.path.append(os.path.join(os.path.dirname(TEST_DIR), "bots/machine"))

from testlib import MachineCase, nondestructive, test_main  # pylint: disable=import-error
from machine_install import VirtInstallMachine

@nondestructive
class TestBasic(MachineCase):
    MachineCase.machine_class = VirtInstallMachine

    def testNavigation(self):
        b = self.browser
        m = self.machine

        b.open("/cockpit/@localhost/anaconda-webui/index.html#/installation-language")

        self.assertIn(
            b.attr("#app > .pf-c-page", "data-debug"),
            ["False", "false", "True", "true"]
        )

        # Check betanag
        value = m.execute("cat /.buildstamp | grep IsFinal=")
        if value.split("=", 1)[1] in ("False", "false"):
            b.wait_visible("#betanag-icon")
        else:
            b.wait_not_present("#betang-icon")

        for page in ['installation-language', 'installation-destination', 'review-configuration']:
            # with the pages basically empty of common elements (as those are provided by the top-level wizard widget)
            # we at least iterate over them to check this works as expected
            b.wait_js_cond(f'window.location.hash === "#/{page}"')
            b.wait_visible("#" + page + ".pf-m-current")
            # Do not start the installation in non-destructive tests as this performs non revertible changes
            if page != 'review-configuration':
                b.click("button.pf-m-primary")
            if page == 'installation-language':
                b.expect_load()

        # Ensure that the 'actual' UI process is running/
        self.assertIn("/usr/libexec/webui-desktop", m.execute("ps aux"))

if __name__ == '__main__':
    test_main()
