#!/usr/bin/python3
#
# Copyright (C) 2021 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; If not, see <http://www.gnu.org/licenses/>.

import os
import sys

# import Cockpit's machinery for test VMs and its browser test API
TEST_DIR = os.path.dirname(__file__)
sys.path.append(os.path.join(TEST_DIR, "common"))
sys.path.append(os.path.join(os.path.dirname(TEST_DIR), "bots/machine"))

from testlib import MachineCase, nondestructive, test_main  # pylint: disable=import-error

@nondestructive
class TestLanguage(MachineCase):

    def testLanguageSwitching(self):
        b = self.browser

        b.open("/cockpit/@localhost/anaconda-webui/index.html")

        # Expect the default language - this is en at this point - adjust the test when better guess is implemented
        b.wait_in_text(".pf-c-form__label-text", "What language would you like to use during the installation process?")

        b.wait_val("#language-menu-toggle-select-typeahead", "English (United States)")

        # Check that the [x] button clears the input text
        b.click(".pf-c-select__toggle-clear")
        b.wait_val("#language-menu-toggle-select-typeahead", "")

        # Check that the language menu shows all menu entries when clicking the toggle button
        b.click("#language-menu-toggle")
        b.wait_visible("#English--English-")
        b.wait_visible("#Deutsch--German-")

        # Check that the language menu shows filtered menu entries
        b.set_input_text("#language-menu-toggle-select-typeahead", "Deutsch")
        b.wait_visible("#Deutsch--German-")
        b.wait_not_present("#English--English-")

        # Select the 'German' language
        b.click("#de_DE > button")
        b.expect_load()
        b.wait_val("#language-menu-toggle-select-typeahead", "Deutsch (Deutschland)")

        b.wait_in_text(".pf-c-form__label-text", "Welche Sprache möchten Sie während des Installationsvorgangs verwenden?")

        # TODO: Add checks for translated plurals

if __name__ == '__main__':
    test_main()
