#!/usr/bin/python3
#
# Copyright (C) 2022 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; If not, see <http://www.gnu.org/licenses/>.

import anacondalib

from installer import Installer
from progress import Progress
from storage import Storage
from users import create_user
from utils import add_public_key, get_pretty_name
from testlib import test_main  # pylint: disable=import-error


class TestInstallationProgress(anacondalib.VirtInstallMachineCase):

    def testBasic(self):
        # HACK Ignore some selinux errors
        self.allow_journal_messages(".*denied.*comm=\"tar\" name=\"/\".*")
        self.allow_browser_errors(".*client closed.*")
        self.allow_browser_errors(".*Server has closed the connection.*")

        b = self.browser
        m = self.machine
        i = Installer(b, self.machine)
        p = Progress(b)
        s = Storage(b, self.machine)

        i.open()

        # Create user on the first pass through users step
        i.reach(i.steps.REVIEW, step_callbacks={i.steps.ACCOUNTS: lambda: create_user(self, cleanup=False)})
        i.begin_installation()

        # the warning can take longer to show up than the regular wait_in_text() timeout
        with b.wait_timeout(600):
            b.wait_in_text("h2", "Successfully installed")
            b.wait_in_text(".pf-v5-c-empty-state", f"To begin using {get_pretty_name(m)}, reboot your system")

        # Pixel test the complete progress step
        b.assert_pixels(
            "#app",
            "installation-progress-complete",
            ignore=["#betanag-icon"],
        )

        p.wait_done()
        add_public_key(self.machine)
        p.reboot()
        m.wait_reboot()

if __name__ == '__main__':
    test_main()
