#!/usr/bin/python3
#
# Copyright (C) 2022 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; If not, see <http://www.gnu.org/licenses/>.

import anacondalib

from installer import Installer
from password import Password
from review import Review
from users import Users, CREATE_ACCOUNT_ID_PREFIX, create_user, dbus_reset_users
from testlib import nondestructive, test_main, sit  # pylint: disable=import-error

@nondestructive
class TestUsers(anacondalib.VirtInstallMachineCase):
    def setUp(self):
        super().setUp()

    def testBasic(self):
        b = self.browser
        i = Installer(b, self.machine)
        u = Users(b, self.machine)

        self.addCleanup(lambda: dbus_reset_users(self.machine))

        i.open()

        i.reach(i.steps.ACCOUNTS)
        create_user(b, self.machine)
        b.assert_pixels(
            "#app",
            "users-step-basic",
            ignore=["#betanag-icon"],
        )
        i.reach(i.steps.REVIEW)

        users = u.dbus_get_users()
        self.assertIn('"groups" as 1 "wheel"', users)
        self.assertIn('"is-crypted" b false', users)
        self.assertIn('"password" s "password"', users)

    @staticmethod
    def _test_user_account(user, installer, valid, invalid):
        installer.check_next_disabled(disabled=False)

        n_valid = len(valid) - 1
        n_invalid = len(invalid) - 1

        # Set valid and invalid value in turns and check the next button
        for i in range(max(n_valid, n_invalid)):
            i_valid = min(i, n_valid)
            i_invalid = min(i, n_invalid)
            user.set_user_account(invalid[i_invalid])
            installer.check_next_disabled()
            user.set_user_account(valid[i_valid])
            installer.check_next_disabled(disabled=False)

    def testAccessAndValidation(self):
        b = self.browser
        i = Installer(b, self.machine)
        p = Password(b, CREATE_ACCOUNT_ID_PREFIX)
        u = Users(b, self.machine)

        self.addCleanup(lambda: dbus_reset_users(self.machine))

        i.open()

        i.reach(i.steps.ACCOUNTS)

        # Fill in valid values
        password = "password"
        full_name = "Full Tester"
        user_account = "tester"

        p.set_password(password)
        p.set_password_confirm(password)
        u.set_full_name(full_name)
        u.set_user_account(user_account)

        p.check_password(password)
        p.check_password_confirm(password)
        u.check_full_name(full_name)
        u.check_user_account(user_account)

        # Test that you can move forward and going back keeps values
        i.next()
        i.back()
        p.check_password(password)
        p.check_password_confirm(password)
        u.check_full_name(full_name)
        u.check_user_account(user_account)

        # Test that moving back and forward keeps values
        i.back()
        i.next()
        p.check_password(password)
        p.check_password_confirm(password)
        u.check_full_name(full_name)
        u.check_user_account(user_account)

        # Test full name validation
        u.set_full_name("")
        i.check_next_disabled(disabled=False)
        u.set_full_name(full_name)

        # Test account validation
        # FIXME this should be tested by unit tests?
        invalid_user_accounts = [
            "",
            # reserved
            "root", "system", "daemon", "home",
            "33333",
            ".",
            "..",
            "-tester",
            "123",
            "$",
            "$tester",
            "tester?",
            "longer_than_32_characteeeeeeeeeeeeeeeeeeers",
        ]
        valid_user_accounts = [
            "tester-",
            "...",
            "12.3",
            "tester1",
            "tester$",
            "test-er",
            "test_er",
            "test.er",
            "_tester",
            ".tester",
            "_",
        ]
        self._test_user_account(u, i, valid_user_accounts, invalid_user_accounts)
        u.set_user_account(user_account)

        # Test password validation
        # No password set
        p.set_password("")
        p.set_password_confirm("")
        p.check_pw_rule("length", "indeterminate")
        p.check_pw_rule("match", "indeterminate")
        i.check_next_disabled()
        # Start which pw which is too short
        p.set_password("abcd")
        p.check_pw_strength(None)
        i.check_next_disabled()
        p.check_pw_rule("length", "error")
        p.check_pw_rule("match", "error")
        # Make the pw 6 chars long
        p.set_password("ef", append=True, value_check=False)
        i.check_next_disabled()
        p.check_password("abcdef")
        p.check_pw_rule("length", "success")
        p.check_pw_rule("match", "error")
        p.check_pw_strength("weak")
        # Set the password confirm
        p.set_password_confirm("abcde")
        p.check_pw_rule("match", "error")
        p.set_password_confirm("abcdef")
        p.check_pw_rule("match", "success")
        p.check_pw_rule("length", "success")
        p.check_pw_strength("weak")
        i.check_next_disabled(disabled=False)

        # Test password strength
        p.set_password("Rwce82ybF7dXtCzFumanchu!!!!!!!!")
        p.check_pw_strength("strong")

        # Test review values
        p.set_password(password)
        p.set_password_confirm(password)
        u.set_full_name(full_name)
        u.set_user_account(user_account)
        r = Review(b)
        i.reach(i.steps.REVIEW)
        r.check_account(f"{full_name} ({user_account})")


if __name__ == '__main__':
    test_main()
