#!/usr/bin/python3

# Copyright (C) 2022 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; If not, see <http://www.gnu.org/licenses/>.

import argparse
import os
import subprocess
import sys

WEBUI_TEST_DIR = os.path.normpath(os.path.dirname(__file__))

def download_image(image=''):
    image_file = os.path.join(WEBUI_TEST_DIR, "images", image)
    if image == 'fedora-rawhide':
        subprocess.Popen(
            f"curl -L https://download.fedoraproject.org/pub/fedora/linux/development/rawhide/Server/x86_64/os/images/boot.iso -o {image_file}",
            shell=True
        ).wait()
        return True
    else:
        sys.stderr.write("image-download: Not supported test image\n")
        return False

def main():
    parser = argparse.ArgumentParser(description='Download an iso image')
    parser.add_argument('image')
    args = parser.parse_args()

    if not download_image(args.image):
        return 1

    return 0


if __name__ == '__main__':
    sys.exit(main())
