#!/bin/bash

set -eu

# FIXME boot.iso on rawhide does not currently contain the new cockpit dependencies
# This will change once we include this changes upstream and start building boot.iso with the new dependencies
# Then we can safely remove this workaround
ANACONDA_WEBUI_DEPS_URLS='
    https://kojipkgs.fedoraproject.org//packages/cockpit/292/1.fc39/x86_64/cockpit-ws-292-1.fc39.x86_64.rpm
    https://kojipkgs.fedoraproject.org//packages/cockpit/292/1.fc39/x86_64/cockpit-bridge-292-1.fc39.x86_64.rpm
    https://kojipkgs.fedoraproject.org/packages/firefox/114.0/1.fc39/x86_64/firefox-114.0-1.fc39.x86_64.rpm
    https://kojipkgs.fedoraproject.org/packages/dbus-glib/0.112/5.fc38/x86_64/dbus-glib-0.112-5.fc38.x86_64.rpm
'

mkdir -p tmp/extra-rpms
pushd tmp/extra-rpms
for url in $ANACONDA_WEBUI_DEPS_URLS; do
    test -e "$(basename "${url}")" || curl -LO "$url"
done
# shellcheck disable=SC2086,SC2046
ANACONDA_WEBUI_DEPS_RPMS="$(realpath $(basename -a ${ANACONDA_WEBUI_DEPS_URLS}))"
popd

# switch to root of the repository
pushd ../..
# remove old rpms and build new srpm
rm -rf ../../result/build
make srpm
popd

# build the anaconda srpm (and result RPMs go in `tmp/rpms`)
test/build-rpms -v ../../result/build/00-srpm-build/anaconda-*.src.rpm

# makeupdates must be run from the top level of the anaconda source tree
pushd ../../
# shellcheck disable=SC2086,SC2046
scripts/makeupdates --add ui/webui/tmp/rpms/anaconda-*.rpm ${ANACONDA_WEBUI_DEPS_RPMS}
popd
