#!/bin/bash

set -eu

# switch to root of the repository
pushd ../..
# remove old rpms and build new srpm
rm -rf ../../result/build
make srpm
popd

# build the anaconda srpm (and result RPMs go in `tmp/rpms`) && download cockpit RPMs
test/build-rpms -v ../../result/build/00-srpm-build/anaconda-*.src.rpm

# makeupdates must be run from the top level of the anaconda source tree
pushd ../../
# shellcheck disable=SC2086,SC2046
scripts/makeupdates --add ui/webui/tmp/rpms/anaconda-*.rpm ui/webui/tmp/rpms/cockpit-*.rpm ui/webui/tmp/rpms/firefox-*.rpm ui/webui/tmp/rpms/dbus-glib-*.rpm
popd
