 
                09Velkomin(n) í 0cRed Hat09 Linux @VERSION@!07

 -  Til að setja upp eða uppfæra 0cRed Hat07 Linux í myndrænum ham, 
    sláðu á 0f<ENTER>07 hnappinn.

 -  Til að setja upp eða uppfæra 0cRed Hat07 Linux í textaham, sláðu inn: 0ftext <ENTER>07.

 -  Til að nota lága upplausn, sláðu inn: 0flowres <ENTER>07.  
    Sláðu á 05<F2>07 fyrir frekari upplýsingar um lágupplausnarham.

 -  Til að nota ekki framebuffer-ham, sláðu inn: 0fnofb <ENTER>07.  
    Sláðu á 05<F2>07 fyrir frekari upplýsingar um að slökkvba á framebuffer.

 -  Ef þú vilt fara í sérfræðingsham, sláðu inn: 0fexpert <ENTER>07.  
    Sláðu á 05<F3>07 fyrir frekari upplýsingar um sérfræðingsham.

 -  Til að komast í björgunarham, sláðu inn: 0flinux rescue <ENTER>07.  
    Sláðu á 05<F5>07 fyrir frekari upplýsingar um björgunarham.

 -  Ef þú ert með rekladiskling, sláðu inn: 0flinux dd <ENTER>07.

 -  Einnig getur þú notað hnappana hgér að neðan fyrir frekari upplýsingar.

05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07
