

                        09Hjálp um sérfræðingsham07

Sjálfgefna aðferðin ti lað setja upp 0cRed Hat07 Linux leitar sjálfvirkt
að vélbúnaði og stillingum vélbúnaðar í vélinni þinni. Þó það gengi vel
á flestum kerfum getur þetta ollið vandræðum í sumum tilfellum.
Það er hægt að komast hjá þeim með því að nota sérfræðingshaminn

Til að hefja uppsetningu í sérfræðingsham, sláðu inn 0fexpert <ENTER>07.

Meðan þú ert í sérfræðingsham hefur þú fulla stjórn á öllum liðum
uppsetningarinnar. Þú getur einnig slegið inn rofa og/eða viðföng
við kjarnaeiningum í sérfræðingsham.










05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07
