

                        09Rescue Mode Help07

The 0cRed Hat07 Linux CD-ROM includes a rescue mode which can be used
when a system does not boot properly.  The rescue mode includes many
useful utilities (editor, hard drive and RAID tools, etc.) which will allow
one to restore a system to a working state.

To enter the rescue mode, boot your system from the 0cRed Hat07 Linux 
CDROM and type 0flinux rescue <ENTER>07.












05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07
