#!/usr/bin/python
#
# scan system for common hardware types
#
# Copyright (C) 2007  Red Hat, Inc.  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import os
import sys
import string

from kudzu import *


def doScan(devclass, bus, type):
    try:
	devs = probe(devclass, bus, type)
    except:
	devs = []

    return devs

def printResults(devs):
    if len(devs) < 1:
	print "    None detected."
	print
    else:
	for dev in devs:
	    print "   Device %s:" % (dev.desc,)
	    s = str(dev)
	    for l in string.split(s, '\n'):
		print "     ",l

	print

#
# start
#
print

print "Scanning for Mice"
printResults(doScan(CLASS_MOUSE, BUS_UNSPEC, PROBE_ALL))

print "Scanning for Video Cards"
printResults(doScan(CLASS_VIDEO, BUS_UNSPEC, PROBE_ALL))

print "Scanning for Monitor"
printResults(doScan(CLASS_MONITOR, BUS_DDC, PROBE_ALL))

print "Scanning for Network Adapters"
printResults(doScan(CLASS_NETWORK, BUS_UNSPEC, PROBE_ALL))

print "Scanning for SCSI Controllers"
printResults(doScan(CLASS_SCSI, BUS_PCI, PROBE_ALL))

print "Scanning for SATA Controllers"
printResults(doScan(CLASS_SATA, BUS_PCI, PROBE_ALL))

print "Scanning for PCMCIA Controllers"
printResults(doScan(CLASS_SOCKET, BUS_PCI, PROBE_ALL))

print "Scanning for USB Controllers"
printResults(doScan(CLASS_USB, BUS_PCI, PROBE_ALL))

print "Scanning for FIREWIRE Controllers"
printResults(doScan(CLASS_FIREWIRE, BUS_PCI, PROBE_ALL))

