#!/usr/bin/python
#
# scan system for common hardware types
#

import os
import sys
import string

from kudzu import *


def doScan(devclass, bus, type):
    try:
	devs = probe(devclass, bus, type)
    except:
	devs = []

    return devs

def printResults(devs):
    if len(devs) < 1:
	print "    None detected."
	print
    else:
	for dev in devs:
	    print "   Device %s:" % (dev.desc,)
	    s = str(dev)
	    for l in string.split(s, '\n'):
		print "     ",l

	print

#
# start
#
print

print "Scanning for Mice"
printResults(doScan(CLASS_MOUSE, BUS_UNSPEC, PROBE_ALL))

print "Scanning for Video Cards"
printResults(doScan(CLASS_VIDEO, BUS_UNSPEC, PROBE_ALL))

print "Scanning for Monitor"
printResults(doScan(CLASS_MONITOR, BUS_DDC, PROBE_ALL))

print "Scanning for Network Adapters"
printResults(doScan(CLASS_NETWORK, BUS_UNSPEC, PROBE_ALL))

print "Scanning for SCSI Controllers"
printResults(doScan(CLASS_SCSI, BUS_PCI, PROBE_ALL))

print "Scanning for SATA Controllers"
printResults(doScan(CLASS_SATA, BUS_PCI, PROBE_ALL))

print "Scanning for PCMCIA Controllers"
printResults(doScan(CLASS_SOCKET, BUS_PCI, PROBE_ALL))

print "Scanning for USB Controllers"
printResults(doScan(CLASS_USB, BUS_PCI, PROBE_ALL))

print "Scanning for FIREWIRE Controllers"
printResults(doScan(CLASS_FIREWIRE, BUS_PCI, PROBE_ALL))

