#!/usr/bin/python
#
# list-harddrives-stub
#
# Copyright (C) 2007, 2009, 2011  Red Hat, Inc.  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import parted


def main():

    def get_devices():
        devices = parted.getAllDevices()
        devices = [d for d in devices if d.type != parted.DEVICE_DM]
        for dev in devices:
            path = dev.path[5:] if dev.path.startswith('/dev/') else dev.path
            yield path, dev.getSize()

    for dev, size in sorted(set(get_devices())):
        print dev, size


if __name__ == '__main__':
    main()
