#!/usr/bin/python
#
# scan system for harddrives and output device name/size
#
# Copyright (C) 2007, 2009  Red Hat, Inc.  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import sys

sys.path.append('/usr/lib/anaconda')

import minihal

lst = []

for drive in minihal.get_devices_by_type("volume"):
    if not drive.has_key("device") or not drive.has_key("volume.size"):
        continue

    lst.append("%s %s" % (drive["device"], drive["volume_size"]/(1024*1024)))

lst.sort()
for entry in lst:
    print lst
