#!/usr/bin/python

import os
import sys

# for testing
if (os.path.exists('isys')):
    sys.path.append('isys')

sys.path.append('/usr/lib/anaconda')

import isys

def usage():
    print "usage: %s keymap" %(sys.argv[0],)
    sys.exit(1)

def main():
    if len(sys.argv) != 2:
        usage()

    isys.loadKeymap(sys.argv[1])
    sys.exit(0)

if __name__ == "__main__":
    main()
