#!/usr/bin/python
#
# loadkeys-stub
#
# Copyright (C) 2007, 2011  Red Hat, Inc.  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import sys

sys.path.append('/usr/lib/anaconda')
import isys


def usage():
    return 'Usage: %prog <keymap>'


def main(prog, args):

    def err(msg):
        sys.stderr.write('%s: %s\n' % (prog, msg))
        sys.exit(1)

    if len(args) > 1:
        err("extra operand '%s'" % args[1])

    try:
        keymap = args[0]
    except IndexError:
        err('missing operand')

    try:
        isys.loadKeymap(keymap)
    except SystemError as e:
        err(e)


if __name__ == '__main__':
    main(prog=sys.argv[0], args=sys.argv[1:])
