#!/usr/bin/python
#
# losetup-stub
#
# Copyright (C) 2007  Red Hat, Inc.  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import os
import sys

from pyanaconda import isys
from sys import argv

def usage():
    print "usage: losetup [-d] /dev/loopN [image]"
    sys.exit(1)

if len(argv) < 3:
    usage()

if argv[1] == "-d" and len(argv[2]) > 4 and argv[2][-5:-1] == "loop":
    try:
        isys.unlosetup(argv[2])
    except SystemError, (errno, msg):
        print msg
        sys.exit (1)
    sys.exit(0)

if len(argv[1]) > 4 and argv[1][-5:-1] == "loop":
    try:
        isys.losetup(argv[1], argv[2])
    except SystemError, (errno, msg):
        print msg
        sys.exit (1)
    sys.exit(0)

usage()
