#!/usr/bin/python

import os
import sys

# for testing
if (os.path.exists('rpmmodule')):
    sys.path.append('rpmmodule')
    sys.path.append('libfdisk')
    sys.path.append('balkan')
    sys.path.append('kudzu')
    sys.path.append('gnome-map')
    sys.path.append('isys')

sys.path.append('/usr/lib/anaconda')

import anaconda_log
import fsset
import raid
import isys
from sys import argv

if len(argv) != 2 or argv[1][:7] != "/dev/md":
    print "usage: raidstop /dev/md[minornum]"
    sys.exit(1)

isys.raidstop(argv[1][5:])
