#!/usr/bin/python
#
#
# Stub to start X in rescue mode with twm and an xterm
#

import os, sys
import rhpxl.xserver as xserver
import rhpl.keyboard as keyboard

# see if its even possible
if not os.access("/mnt/sysimage/usr/X11R6/bin/xterm", os.X_OK) or not os.access("/mnt/sysimage/usr/X11R6/bin/twm", os.X_OK):
    print "Must have mounted an existing installation in rescue mode to work."
    sys.exit(0)

if len(sys.argv) > 1:
    mode = sys.argv[1]
else:
    mode = '800x600'

xserver.probeHWandStartXServer(mode)
os.system("xterm&")
os.system("twm")
