# Settings for infrastructure autogeneration
#
# See also:
#     scripts/jinja-render
#     make reload-infra
#
# Follow "type hints" below or be sad. The choice is yours.

distro_name: "fedora" # "fedora" or "rhel"
distro_release: 43 # "rawhide" or a number without quotation marks

# The following only applies for rawhide.
rawhide_fedora_version: 43 # number without quotation marks, or nothing if CI should not run for branched Fedora

# List of all the branches which are currently supported and CI should be executed on these.
supported_branches:
  - rhel-9:
    variant: "rhel"
  - rhel-10:
    variant: "rhel"
