# Settings for infrastructure autogeneration
#
# See also:
#     scripts/jinja-render
#     make reload-infra
#
# Follow "type hints" below or be sad. The choice is yours.

distro_name: "fedora" # "fedora" or "rhel"
distro_release: "rawhide" # "rawhide" or a number without quotation marks
branch_name: "main"

# The following only applies for rawhide.
rawhide_fedora_version: 45 # number without quotation marks, or nothing if CI should not run for branched Fedora

# List of supported releases. Each release can track its own branch or derive from main.
# - release: string identifier (e.g., "rhel-9", "fedora-43")
# - target_branch: git branch to check out for this release
# - variant: optional, "rhel" or "fedora" or "eln"
supported_releases:
  - release: "fedora-rawhide"
    target_branch: "main"
    variant: "fedora"
  - release: "rhel-9"
    target_branch: "rhel-9"
    variant: "rhel"
  - release: "rhel-10"
    target_branch: "rhel-10"
    variant: "rhel"
  - release: "fedora-eln"
    target_branch: "main"
    variant: "eln"
  - release: "fedora-44"
    target_branch: "main"
    variant: "fedora"

# List of all the branches which should get translation updates
translation_branches:
  - rhel-9:
    variant: "rhel"
  - rhel-10:
    variant: "rhel"
