specfile_path: anaconda.spec
upstream_package_name: anaconda
upstream_tag_template: anaconda-{version}-1
actions:
  post-upstream-clone:
    - ./autogen.sh
    - ./configure
  create-archive:
    - "make release"
    - 'bash -c "ls -1 anaconda-*.tar.bz2"'
jobs:
  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-rawhide
