#!/usr/bin/python

import os, sys, pdb

if (os.path.exists('isys')):
    sys.path.append('edd')
    sys.path.append('libfdisk')
    sys.path.append('balkan')
    sys.path.append('gnome-map')
    sys.path.append('isys')
    sys.path.append('textw')
    sys.path.append('iw')
    sys.path.append('installclasses')
    sys.path.append('edd')
else:
    sys.path.append('/usr/lib/anaconda')
    sys.path.append('/usr/lib/anaconda/textw')
    sys.path.append('/usr/lib/anaconda/iw')
    sys.path.append('/usr/lib/anaconda/installclasses')

from cPickle import Unpickler

f = open("anacdump.txt")

line = f.readline()
while (line != "ToDo object:\n"):
    line = f.readline()

up = Unpickler(f)
todo = up.load()

pdb.set_trace()
