 
                  09Bienvenido a 0cRed Hat09 Linux @VERSION@07

 -  Para instalar o actualizar 0cRed Hat07 Linux en modo gr fico, pulse 0f<ENTER>07.

 -  Para instalar o actualizar 0cRed Hat07 Linux en modo texto, teclee:
    0ftext <ENTER>07.

 -  Para activar el modo de baja resoluci¢n, teclee: 0flowres <ENTER>07.  
    Pulse 05<F2>07 para m s informaci¢n sobre el modo de baja resoluci¢n.

 -  Para desactivar el modo framebuffer, teclee: 0fnofb <ENTER>07.  
    Pulse 05<F2>07 para m s informaci¢n sobre desactivar el modo framebuffer.

 -  Para activar el modo experto, teclee: 0fexpert <ENTER>07.  
    Pulse 05<F3>07 para m s informaci¢n sobre el modo experto.

 -  Para activar el modo rescate, teclee: 0flinux rescue <ENTER>07.  
    Pulse 05<F5>07 para m s informaci¢n sobre el modo rescate.

 -  Si tiene un disco de drivers, teclee: 0flinux dd <ENTER>07.

 -  Use las teclas de funci¢n mostradas abajo para conseguir m s informaci¢n.

  05[F1-Principal]   [F2-General]   [F3-Experto]   [F4-Kernel]   [F5-Rescate]07
