
 
                09Bienvenido a 0cRed Hat09 Linux 7.007

 o  Para instalar o actualizar un sistema que funcione con 0cRed Hat07
    Linux 3.0.3 o con una versi¢n posterior en modo gr fico (graphic), pulse:
    0f<ENTER>07.

 o  Para instalar o actualizar un sistema que funcione con 0cRed Hat07
    Linux 3.0.3 o con una versi¢n posterior en modo texto (text) teclee:
    0ftext <ENTER>07.

 o  Para activar el modo experto (expert) teclee: 0fexpert <ENTER>07. Pulse
    05<F3>07 para obtener mayor informaci¢n sobre el modo experto.

 o  Para activar el modo rescate (rescue) teclee: 0flinux rescue <ENTER>07.
    Pulse 05<F5>07 para obtener mayor informaci¢n sobre el modo rescate.

 o  Si tiene una unidad disco, teclee: 0flinux dd <ENTER>07.

 o  Utilice las teclas de funci¢n que se muestran a continuaci¢n para obtener
    mayor informaci¢n.


05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07
