


                 09Bienvenidos a 0cRed Hat09 Linux 6.2!07

 o  Para instalar o actualizar un sistema con 0cRed Hat07 Linux 2.0 
    o superior en modo gr fico, pulse la tecla 0f<ENTER>07.

 o  Para instalar o actualizar un sistema con 0cRed Hat07 Linux 2.0 
    o superior en modo texto, teclee 0ftext <ENTER>07.

 o  Para activar el modo experto, teclee: 0fexpert <ENTER>07.
    Pulse 05<F3>07 para obtener m s informaci¢n ver modo experto.

 o  Para activar el modo de recuperaci¢n, teclee: 0frescue <ENTER>07.
    Pulse 05<F5>07 para obtener m s informaci¢n ver modo de recuperaci¢n.

 o  Si tiene un disquete con los driver, teclee 0flinux dd <ENTER>07.
 
 o  Pulse las teclas funci¢n que aparecen en la parte baja de la pantalla
    para obtener m s informaci¢n.



05[F1-Principal] [F2-General] [F3-Experto] [F4-Kernel] [F5-Recuperaci¢n]07
