

                        09Ayuda para el modo experto(expert)07

El m‚todo de instalaci¢n 0cRed Hat07 Linux realiza por defecto 
un chequeo para detectar autom ticamente el hardware de su sistema. Aunque
la mayor¡a de los sistemas pueden ser comprobados sin dificultad, en
algunos casos puede haber problemas.
Es posible evitar esos problemas usando el modo experto (expert).

Par empezar con la instalaci¢n utilice el modo experto, pulse
0fexpert <ENTER>07.

En modo experto tendr  un completo control sobre el proceso de
instalaci¢n. Podr  introducir par metros opcionales si utiliza este m‚todo.








05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07
