
 
                        09Ayuda modo experto07

La instalaci¢n por defecto 0cRed Hat07 Linux utiliza un chequeo para
reconocer autom ticamente el hardware del sistema. Si bien la mayor 
parte del hardware es reconocido sin dificultad, en algunos casos  
pueden presentarse problemas. Es posible resolverlos usando
el modo experto.

Para iniciar la instalaci¢n en modo experto, teclee 0fexpert <ENTER>07.

En modo experto, tendr  un completo control del proceso de instalaci¢n.
Tambi‚n podr  introducir par metros opcionales en el modo experto.








05[F1-Principal] [F2-General] [F3-Experto] [F4-Kernel] [F5-Recuperaci¢n]07

