
                      09Ayuda para el modo Experto07


El m‚todo de instalaci¢n predeterminado de 0cRed Hat07 Linux prueba a
detectar autom ticamente el hardware de su sistema.  Aunque la mayor¡a de
los sistemas pueden ser comprobados sin dificultad, en algunos casos puede
haber problemas.  Es posible evitar esos problemas usando el modo experto.

Para empezar con la instalaci¢n utilizando el modo experto, pulse
0fexpert <ENTER>07.

En modo experto tendr  un completo control sobre el proceso de instalaci¢n.
Podr  introducir par metros opcionales si utiliza este m‚todo.










  05[F1-Principal]   [F2-General]   [F3-Experto]   [F4-Kernel]   [F5-Rescate]07
