
                    09Ayuda general para el arranque07

Est  preparado para empezar ahora el proceso de instalaci¢n.  En muchos
casos, el mejor modo de empezar es simplemente pulsando 0f<ENTER>07. 

El instalador gr fico usa framebuffer con una resoluci¢n de 800x600 y con
una profundidad de color de 16 bits.  Si tiene problemas con la instalaci¢n
gr fica, pruebe una de las siguientes opciones:
  - Inicie el instalador en una resoluci¢n de 640x480 tecleando 0flowres <ENTER>07.
  - Evite usar el modo framebuffer tecleando 0fnofb <ENTER>07.
  - Intente otra resoluci¢n agregando 'vga=xxx'. Posibles valores de vga:
         1024x768x8bpp  -> vga=773        1024x768x16bpp  -> vga=791 
         1280x1024x8bpp -> vga=775        1280x1024x16bpp -> vga=794

En determinadas configuraciones de hardware, durante la instalaci¢n, pueden
darse errores en la detecci¢n autom tica del mismo.  Si experimenta problemas
durante la instalaci¢n, rein¡ciela utilizando el modo experto.  Pulse 05<F3>07
para obtener m s informaci¢n sobre el modo experto.

Existen una serie de par metros que pueden ser pasados al kernel de Linux
durante el proceso de arranque.  Pulse 05<F4>07 para obtener m s informaci¢n. 


  05[F1-Principal]   [F2-General]   [F3-Experto]   [F4-Kernel]   [F5-Rescate]07
