

                        09Ayuda general para el arranque07

Puede cargar el proceso de instalaci¢n 0cRed Hat07 Linux, y empezar el 
proceso desde este prompt. En muchos casos, el mejor modo de
empezar es simplemente pulsar 0f<ENTER>07.

En determinadas configuraciones del hardware durante la instalaci¢n pueden
darse errores en la detecci¢n autom tica del hardware. Pero no es muy normal,
sucede en raras ocasiones. Si se dan problemas durante la instalaci¢n,
vuelva a empezar y utilice el modo experto (expert). Pulse 05<F3>07 
para obtener mayor informaci¢n sobre el modo experto.

Existe una serie de par metros que pueden ser introducidos en el kernel de
Linux durante el arranque. Pero no se dan par metros para dispositivos como 
CD-ROM o tarjetas ethernet. Pulse 05<F4>07 para obtener mayor informaci¢n. 






05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07
