

                    09Ayuda general para el inicio07

Es posible activar la instalaci¢n de 0cRed Hat07 Linux, directamente 
desde este " prompt".  En la mayor¡a de los casos, la mejor manera de
empezar es simplemente pulsando 0f<ENTER>07.

Algunas configuraciones hardware podr¡an crear problemas durante el
reconocimiento autom tico del hardware. Aunque no es lo normal, puede
suceder.  Si se presenta cualquier problema durante el proceso de instalaci¢n,
reactive el sistema usando la modalidad para expertos.  Pulse 05<F3>07
para obtener m s infomaci¢n sobre la modo experto.

Existen varios par metros que pueden ser pasados al kernel de Linux desde el
inicio del sistema. No es posible introducir los par metros para dispositivos
como CD-ROM o tarjetas de red. Pulse 05<F5>07 para m s informaci¢n. 





05[F1-Principal] [F2-General] [F3-Experto] [F4-Kernel] [F5-Recuperaci¢n]07

