
                   09Ayuda sobre los par metros del Kernel07


Algunos par metros del kernel pueden ser introducidos en la l¡nea de comandos
y dichos par metros le ser n pasados al kernel.  Esto no incluye a m¢dulos de 
dispositivos tales como tarjetas ethernet o unidades de CD-ROM.

Para pasar una opci¢n al kernel, utilice el siguiente formato:
     0flinux <opciones>07
Si desea un modo diferente de instalaci¢n, ins‚rtelo despu‚s de las opciones.

Por ejemplo, para hacer la instalaci¢n en un sistema con 128MB de RAM usando
el modo experto, teclee lo siguiente:
     0flinux mem=128M expert07

Para pasar opciones a los m¢dulos, necesitar  usar el modo experto que
inhabilitar  la detecci¢n autom tica de dispositivos PCI.  Cuando el programa
de instalaci¢n le pregunte sobre el tipo de dispositivo al que necesita
pasarle una opci¢n o un par metro, en ese momento, ver  un lugar donde poder
introducirle dichos par metros.



  05[F1-Principal]   [F2-General]   [F3-Experto]   [F4-Kernel]   [F5-Rescate]07
