




                        09Ayuda Par metros del Kernel07

Algunos par metros del kernel pueden ser especificados en la l¡nea de
comandos y son pasados directamente al kernel. No es posible introducir
opciones para las tarjetas como las ethernet o dispositivos como las
unidades de CD-ROM.

Para pasar una opci¢n al kernel, es necesario usar el siguiente formato:
     0flinux <options>07
Si se desea utilizar un m‚todo particular de instalaci¢n, escribirlo
 despu‚s de las opciones.
Por ejemplo, para la instalaci¢n sobre un sistema con 128MB de RAM en moda
lidad para expertos, teclee el siguiente comando:
     0flinux mem=128M expert07

Para pasar las opciones a las tarjetas, es necesario usar el modo experto
e inhabilitar el autochequeo de PCI. Cuando el programa de instalaci¢n
le pregunte por un dispositivo que necesite opciones o par metros,
habr  un lugar donde podr  introducirlos en ese momento.

05[F1-Principal] [F2-General] [F3-Experto] [F4-Kernel] [F5-Recuperaci¢n]07



