

                        09Ayuda del modo de recuperaci¢n07

El CDROM de 0cRed Hat07 Linux incluye el modo de recuperaci¢n que puede ser
usado cuando el sistema no se inicia adecuadamente. El modo de recuperaci¢n
incluye numerosas utilidades (editor, herramientas para discos duros y RAID,
etc.) las cuales le permitir n devolver el sistema a la normalidad.

Para activar el modo de recuperaci¢n, inicie el sistema con el CDROM 
0cRed Hat07 Linux, y teclee 0flinux rescue <ENTER>07.












05[F1-Principal] [F2-General] [F3-Experto] [F4-Kernel] [F5-Recuperaci¢n]07

