

                        09Ayuda para el modo rescate(rescue)07

El CD-ROM de 0cRed Hat07 Linux incluye el modo rescate (rescue) que puede
ser usado cuando un sistema no consigue arrancar apropiadamente. El modo
rescate incluye numerosas utilidades (editor, herramientas para el disco duro
y RAID, etc.) lo que permite reestructurar el funcionamiento del sistema.

Para utilizar el modo rescate, arranque su sistema desde el CD ROM
0cRed Hat07 Linux y pulse 0flinux rescue <ENTER>07.












05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07
