
                     09Ayuda para el modo rescate07


El CD-ROM de 0cRed Hat07 Linux incluye un modo de rescate que puede ser
usado cuando un sistema no consigue arrancar adecuadamente.  El modo rescate 
incluye numerosas utilidades (editor, herramientas para discos duros y RAID,
etc...) que le permitir n restaurar el sistema.

Para entrar en el modo rescate, arranque su sistema desde el CD ROM
0cRed Hat07 Linux y teclee 0flinux rescue <ENTER>07.













  05[F1-Principal]   [F2-General]   [F3-Experto]   [F4-Kernel]   [F5-Rescate]07
