#!/bin/sh

# If $top_srcdir has not been set by automake, import the test environment
if [ -z "$top_srcdir" ]; then
    top_srcdir="$(realpath "$(dirname "$0")/../..")"
    . "${top_srcdir}/tests/testenv.sh"
fi

exec "${top_srcdir}"/tests/pylint/runpylint.py
