#!/usr/bin/python

import _isys

p = _isys.ProbedList()
p.updateNet()
p.updateIde()
p.updateScsi()

i = 0
print "found devices:"
#while (i < len(p)):
#    print "\t", p[i]
#    i = i + 1

print len (p)

for i in p:
    print "\t", i

print "Removable test"
for (dclass, path, comment) in p:
#    print "IDE  Test-> ",path,_isys.isIdeRemovable("/dev/"+path)
#    print "SCSI Test-> ",path,_isys.isScsiRemovable("/dev/"+path)
     import isys
     
     print path, isys.driveIsRemovable(path)
    

