include ../Makefile.inc

all:

depend:

install:
	install -m 644 keymaps-$(ARCH) $(DESTDIR)/$(RUNTIMEDIR)

clean:

i386:
	./updkmaps i386

alpha:
	./updkmaps alpha

sparc:
	./updkmaps sparc

s390:
	./updkmaps s390

s390x:
	./updkmaps s390

ppc:
	./updkmaps ppc
