#!/bin/sh

ARCH=$1
if [ -z "$ARCH" ]; then
    echo "usage: $0 <arch>"
    exit 1
fi

TMPDIR=/tmp/keymaps.$$
TOPDIR=`pwd`

rm -rf $TMPDIR
mkdir -p $TMPDIR

if [ $ARCH = "sparc" ]; then
    PATTERN={i386,sun}
else
    PATTERN=i386
fi

eval find /lib/kbd/keymaps/$PATTERN -name "*.map*" | while read n; do
    /bin/loadkeys `basename $n .gz`
    ../utils/readmap $TMPDIR/`basename $n .map.gz`.map
done

loadkeys us

rm -f $TMPDIR/defkeymap* $TMPDIR/ANSI* $TMPDIR/lt.map

(cd $TMPDIR; $TOPDIR/../utils/mapshdr *.map) > $TMPDIR/hdr
cat $TMPDIR/hdr $TMPDIR/*.map | gzip -9 > keymaps-$ARCH
rm -rf $TMPDIR
