[H[J

                   Welcome to [7mRed Hat[m Linux!

 o  To install or upgrade a system running [7mRed Hat[m Linux 4.0
    or later, press the [7m<ENTER>[m key.

 o  To enable expert mode, type: [7mexpert <ENTER>[m.  Press [7m<3>[m for
    more information about expert mode.

 o  To install using text mode, type [7mtext <ENTER>[m

 o  Use the numeric keys listed below at the beginning of input line
    for more information.







[7m[1-Main] [2-General] [3-Expert] [4-Rescue] [5-Kickstart] [6-Kernel][m
