[H[J

                        [7mExpert Mode Help[m

The default method of installing [7mRed Hat[m Linux uses autoprobing to
automatically detect the hardware in your system.  Although most
systems may be autoprobed without difficulties, in certain cases there
can be problems.  It's possible to overcome these problems by using
expert mode.

To start the installation using expert mode, type [7mexpert <ENTER>[m.

While in expert mode, you will have complete control over the
installation process.  You will also be able to enter optional module
parameters while in expert mode.








[7m[1-Main] [2-General] [3-Expert] [4-Rescue] [5-Kickstart] [6-Kernel][m
