[H[J

                        [7mGeneral Boot Help[m

You can load the [7mRed Hat[m Linux installation program, and begin the 
installation process from this prompt.  In most cases, the best way to
get started is to simply press the [7m<ENTER>[m key.

Certain hardware configurations may have trouble with the automatic hardware
detection done during the installation.  While this is unusual, it does
happen occasionally.  If you experience problems during the installation,
restart the installation using expert mode.  Press [7m<3>[m for more
information on expert mode.

This boot disk can no longer be used as a rescue disk.  Press [7m<4>[m for
information on the new rescue disks.

There are a number of parameters that can be passed to the Linux kernel
at boot time.  These do not include parameters for devices such as
CD-ROM drives or ethernet cards.  Press [7m<6>[m for more information. 



[7m[1-Main] [2-General] [3-Expert] [4-Rescue] [5-Kickstart] [6-Kernel][m
