
                       [7mInstaller Boot Options[m

 -  To disable hardware probing, type: [7mlinux noprobe <ENTER>[m.  

 -  To test the install media you are using, type: [7mlinux mediacheck <ENTER>[m.  

 -  To enable rescue mode, type: [7mlinux rescue <ENTER>[m.  
    Press [7m<F5>[m for more information about rescue mode.

 -  If you have a driver disk, type: [7mlinux dd <ENTER>[m.

 -  To prompt for the use of other install methods such as network
    install when booting from a CD, type [7mlinux askmethod <ENTER>[m.

 -  If you have an installer update disk, type: [7mlinux updates <ENTER[m>.

[7m[F1-Main] [F2-Options] [F3-General] [F4-Kernel] [F5-Rescue][m
