
                        [7mKernel Parameter Help[m

Some kernel parameters can be specified on the command line and will be
passed to the kernel.

To pass an option to the kernel, use the following format:

     [7mlinux <options>[m

If a different installation mode is desired, enter it after the option(s).

For example, to install on a system with 256MB of RAM using noprobe mode, 
type the following:

     [7mlinux mem=256M noprobe[m


[7m[F1-Main] [F2-Options] [F3-General] [F4-Kernel] [F5-Rescue][m
