#!/bin/bash
# hdroot script for anaconda

. /lib/anaconda-lib.sh

[ -f /tmp/root.info ] && . /tmp/root.info

dev="$1"
path="$2"
mount "$dev" "$repodir" || die "Couldn't mount $root"
img=$(find_runtime $repodir$path)
if [ -z "$img" ]; then
    iso=$(check_isodir $repodir$path)
    if [ -n "$iso" ]; then
        mount --move $repodir $isodir
        iso=${isodir}${iso#$repodir}
        mount -o loop,ro $iso $repodir
        img=$(find_runtime $repodir)
    fi
fi
[ -e "$img" ] && exec /sbin/dmsquash-live-root $img
die "Couldn't find a suitable image or tree in $path on $dev
