#!/bin/bash
# nfsroot script for anaconda
# usage: anaconda-nfsroot INTERFACE anaconda-nfs:<server>:<path>[:options]

command -v getarg >/dev/null || . /lib/dracut-lib.sh
. /lib/nfs-lib.sh
. /lib/anaconda-lib.sh

netif="$1"
netroot="${2#anaconda-nfs:}"
info "anaconda using NFS root at $netroot"
mount_nfs "$netroot" "$repodir" "$netif" || warn "Couldn't mount $netroot"
anaconda_live_root_dir $repodir
