#!/bin/bash
# fetch-kickstart-disk - fetch kickstart from a block device

. /lib/dracut-lib.sh
. /lib/anaconda-lib.sh

dev="$1"
path="${2:-/ks.cfg}"

[ -b "$dev" ] || exit 1

info "anaconda: fetching kickstart from $dev:$path"
tmpmnt=$(mkuniqdir /run/install tmpmnt)
if mount -o ro $dev $tmpmnt; then
    cp $tmpmnt$path /tmp/ks.cfg
    umount $tmpmnt
    parse_kickstart /tmp/ks.cfg
else
    warn "Can't get kickstart from $dev:$path"
fi
rmdir $tmpmnt
