
 
                09Welcome to 0cRed Hat09 Linux 6.2!07

 o  To install or upgrade a system running 0cRed Hat07 Linux 2.0 
    or later in graphical mode, press the 0f<ENTER>07 key.

 o  To install or upgrade a system running 0cRed Hat07 Linux 2.0 
    or later in text mode, type: 0ftext <ENTER>07.

 o  To enable expert mode, type: 0fexpert <ENTER>07.  Press 05<F3>07 for
    more information about expert mode.

 o  To enable rescue mode, type: 0flinux rescue <ENTER>07.  Press 05<F5>07
    for more information about rescue mode.

 o  If you have a driver disk, type: 0flinux dd <ENTER>07.

 o  Use the function keys listed below for more information.




05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07
