00


                        01General Boot Help07

You are now ready to begin the installation process.  In most cases, 
the best way to get started is to simply press the 01<ENTER>07 key.

If you are having problems with the graphical installer, you can use the 
'01resolution=<width>x<height>07' option to try and force a
particular resolution. For example, boot with 
'01linux resolution=1024x76807'.  

Certain hardware configurations may have trouble with the automatic hardware
detection done during the installation.  If you experience problems during the 
installation, restart the installation adding the 'noprobe' option.  The
'skipddc' option will also skip monitor probing which hangs some systems.

There are a number of parameters that can be passed to the Linux kernel
at boot time.  Press 01<F4>07 for more information. 


0f[F1-Main] [F2-Options] [F3-General] [F4-Kernel] [F5-Rescue]07

