00
 

                       01Installer Boot Options07

 -  To disable hardware probing, type: 01linux noprobe <ENTER>07.  

 -  To test the install media you are using, type: 01linux mediacheck <ENTER>07.  

 -  To enable rescue mode, type: 01linux rescue <ENTER>07.  
    Press 01<F5>07 for more information about rescue mode.

 -  If you have a driver disk, type: 01linux dd <ENTER>07.

 -  To prompt for the use of other install methods such as network
    install when booting from a CD, type 01linux askmethod <ENTER>07.

 -  If you have an installer update disk, type: 01linux updates <ENTER>07.

 -  To test the memory in your system type: 01memtest86 <ENTER>07.
    (This option is only available when booting from CD.)

0f[F1-Main] [F2-Options] [F3-General] [F4-Kernel] [F5-Rescue]07
