00
 

                       09Installer Boot Options07

 -  To disable hardware probing, type: 0flinux noprobe <ENTER>07.  

 -  To test the install media you are using, type: 0flinux mediacheck <ENTER>07.  

 -  To enable rescue mode, type: 0flinux rescue <ENTER>07.  
    Press 0f<F5>07 for more information about rescue mode.

 -  If you have a driver disk, type: 0flinux dd <ENTER>07.

 -  To prompt for the install method being used on a CD-ROM install, 
    type 0flinux askmethod <ENTER>07.

 -  If you have an installer update disk, type: 0flinux updates <ENTER>07.

 -  To install using a 640x480 resolution, type: 0flinux lowres07.

02[F1-Main] [F2-Options] [F3-General] [F4-Kernel] [F5-Rescue]07
