00


                        09Rescue Mode Help07

The 02Red Hat07 Enterprise Linux installer includes a rescue mode 
which can be used when a system does not boot properly.  The rescue mode 
includes many useful utilities (editor, hard drive and RAID tools, etc.) 
which will allow one to restore a system to a working state.

To enter the rescue mode, boot your system from the 02Red Hat07 
Enterprise Linux CDROM or installation floppy and type 0flinux 
rescue <ENTER>07.





02[F1-Main] [F2-Options] [F3-General] [F4-Kernel] [F5-Rescue]07

