 
                09Welcome to 0cRed Hat09 Linux @VERSION@!07

 -  For å installere eller oppgradere 0cRed Hat07 Linux i grafisk modus, 
    trykk 0f<linjeskift>07.

 -  For å installere eller oppgradere  0cRed Hat07 Linux i tekstmodus,
    skriv: 0ftext <linjeskift>07.

 -  For bruke lavoppløsningsmodus, skriv: 0flowres <linjeskift>07.  
    Trykk 05<F2>07 for mer informasjon om lavoppløsningsmodus.

 -  For å slå av framebuffer modus, skriv: 0fnofb <linjeskift>07.  
    Trykk 05<F2>07 for mer informasjon om å slå av framebuffer modus.

 -  For å bruke ekspertmodus, skriv: 0fexpert <linjeskift>07.  
    Trykk 05<F3>07 for mer informasjon om ekspertmodus.

 -  For å gå til redningsmodus, skriv: 0flinux rescue <linjeskift>07.  
    Trykk 05<F5>07 for mer informasjon om redningsmodus.

 -  Hvis du har en driverdisk, skriv: 0flinux dd <linjeskift>07.

 -  Bruk funksjonstastene som listet under for mer informasjon.

05[F1-Hoved] [F2-Generelt] [F3-Ekspert] [F4-Kjerne] [F5-Redning]07
