

                        09Hjelp for ekspert-modus07

Standard installasjonsmetode for 0cRed Hat07 Linux bruker autosøk for
å gjenkjenne maskinvaren i ditt system. Selv om de fleste systemer
kan kjøre autosøk uten problemer, vil det kunne skape problemer i noen
få tilfeller. Det kan være mulig å løse disse problemene ved å bruke
ekspert-modus.

For å starte installasjonen i ekspert-modus, skriv 0fexpert <Linjeskift>07.

Når du er i ekspert-modus vil du ha full kontroll over selve
installasjonsprosessen. Du vil også kunne oppgi alternative parametere
for moduler i ekspert-modus.








05[F1-Hoved] [F2-Generelt] [F3-Ekspert] [F4-Kjerne] [F5-Redning]07
