

                        09Help for kjerneparametere07

Noen kjerneparametere kan spesifiseres på kommandolinjen og vil derfra bli
sendt videre til kjernen. Dette inkluderer ikke alternativer for moduler for
enheter som nettverkskort eller CD-RPM enheter.

For å sende et flagg til kjernen bruker du følgende format:
     0flinux <flagg>07
Hvis en spesiell installasjonstype er ønsket, skriv den inn etter flaggene.

For eksempel, for å installere et system med 128MB RAM i ekspert-modus,
skriv følgende:
     0flinux mem=128M expert07

For å gi flagg til moduler må du starte ekspert-modus for å slå av
PCI-autosøking. Når instalasjonsprogrammet spør deg etter enhetstype som
trenger et flagg eller en parameter, vil du få muligheten til å oppgi disse
der og da. 



05[F1-Hoved] [F2-Generelt] [F3-Ekspert] [F4-Kjerne] [F5-Redning]07
