

                        09Help for redningsmodus07

0cRed Hat07 Linux CD-ROMen inneholder også redningsmodus som kan brukes
når et system ikke starter riktig. Redningsmodus inkluderer mange
nyttige verktøy (editor, harddisk- og RAID-verktøy etc.) som vil la en
gjenopprette et system fra ikke-fungerende status.

For å bruke redningsmodus, start systemet fra 0cRed Hat07 Linux 
CDROMen og skriv 0flinux rescue <ENTER>07.












05[F1-Hoved] [F2-Generelt] [F3-Ekspert] [F4-Kjerne] [F5-Redning]07
