 
                09Velkommen til 0cRed Hat09 Linux @VERSION@!07

 -  For at installere eller opgradere 0cRed Hat07 Linux i grafisk tilstand, 
    tryk 0f<linjeskift>07.

 -  For at installere eller opgradere  0cRed Hat07 Linux i tekstmodus,
    skriv: 0ftext <linjeskift>07.

 -  For bruge lavopløsningsmodus, skriv: 0flowres <linjeskift>07.  
    Tryk 05<F2>07 for mere information om lavopløsningsmodus.

 -  For at deaktivere framebuffer modus, skriv: 0fnofb <linjeskift>07.  
    Tryk 05<F2>07 for mere information om at deaktivere framebuffer modus.

 -  For at bruge ekspertmodus, skriv: 0fexpert <linjeskift>07.  
    Tryk 05<F3>07 for mere information om ekspertmodus.

 -  For at gå til redningsmodus, skriv: 0flinux rescue <linjeskift>07.  
    Tryk 05<F5>07 for mere information om redningsmodus.

 -  Hvis du har en driverdiskette, skriv: 0flinux dd <linjeskift>07.

 -  Brug funktionstasterne som listet for mere information.

05[F1-Hoved] [F2-Generelt] [F3-Ekspert] [F4-Kerne] [F5-Redning]07
