

                        09Hjælp for ekspert-modus07

Standard installationsmetode for 0cRed Hat07 Linux bruger autosøgning for
at genkende maskinel i dit system. Selv om de fleste systemer
kan køre autosøgning uden problemer, vil det kunne skabe problemer i nogen
få tilfælde. Muligvis kan du løse disse problemer ved at bruge
ekspert-modus.

For at starte installationen i ekspert-modus, skriv 0fexpert <Linjeskift>07.

Når du er i ekspert-modus vil du have fuld kontrol over selve
installationsprocessen. Du vil også kunne opgive alternative parametere
for moduler i ekspert-modus.








05[F1-Hoved] [F2-Generelt] [F3-Ekspert] [F4-Kerne] [F5-Redning]07
