

                        09Hjælp for redningsmodus07

0cRed Hat07 Linux CD-ROMen indeholder også en redningsmodus som kan bruges
når et system ikke starter rigtigt. Redningsmodus inkluderer mange
nyttige værktøjer (editor, harddisk- og RAID-værktøj etc.) som vil lade dig
genoprette et system fra ikke-fungerende status.

For at bruge redningsmodus, start systemet fra 0cRed Hat07 Linux 
CDROMen og skriv 0flinux rescue <ENTER>07.












05[F1-Hoved] [F2-Generelt] [F3-Ekspert] [F4-Kerne] [F5-Redning]07
