

                    09Vaelkommen till 0cRed Hat09 Linux 6.9!07

 o  Foer att installera eller uppgradera ett system som koer 0cRed Hat07 Linux
    3.0.3 eller baettre i grafiskt laege trycker du 0f<ENTER>07-tangenten.

 o  Foer att installera eller uppgradera ett system som koer 0cRed Hat07 Linux
    3.0.3 eller baettre i textlaege skriver du: 0ftext <ENTER>07.

 o  Foer att aktivera expertlaeget skriver du: 0fexpert <ENTER>07.
    Tryck 05<F3>07 foer mer information om expertlaeget.

 o  Foer att aktivera raeddningslaeget skriver du: 0flinux rescue <ENTER>07.
    Tryck 05<F5>07 foer mer information om raeddningslaeget.

 o  Om du har en drivrutinsdiskett skriver du: 0flinux dd <ENTER>07.

 o  Anvaend funktionstangenterna som visas nedan foer mer information.




05[F1-Huvud] [F2-Allmaen] [F3-Expert] [F4-Kaerna] [F5-Raeddning]07
