
                    09Vaelkommen till 0cRed Hat09 Linux 7.0.91!07

 -  Foer att installera eller uppgradera 0cRed Hat07 Linux i grafiskt laege trycker
    du 0f<ENTER>07-tangenten.

 -  Foer att installera eller uppgradera 0cRed Hat07 Linux i textlaege skriver du:
    0ftext <ENTER>07.

 -  Foer att aktivera laagupploesningslaeget skriver du: 0flowres <ENTER>07.
    Tryck 05<F2>07 foer mer information om laagupploesningslaeget.

 -  Foer att deaktivera framebuffer-laeget skriver du: 0fnofb <ENTER>07.  
    Tryck 05<F2>07 foer mer information om deaktivering av framebuffer-laeget.

 -  Foer att aktivera expertlaeget skriver du: 0fexpert <ENTER>07.
    Tryck 05<F3>07 foer mer information om expertlaeget.

 -  Foer att aktivera raeddningslaeget skriver du: 0flinux rescue <ENTER>07.
    Tryck 05<F5>07 foer mer information om raeddningslaeget.

 -  Om du har en drivrutinsdiskett skriver du: 0flinux dd <ENTER>07.
 -  Anvaend funktionstangenterna som visas nedan foer mer information.

05[F1-Huvud] [F2-Allmaen] [F3-Expert] [F4-Kaerna] [F5-Raeddning]07
