
                         09Hjaelp foer expertlaeget07

Standardmetoden som 0cRed Hat07 Linux installeras med anvaender automatisk
testning foer att automatiskt upptaecka haardvaran i ditt system. Aeven om de
flesta system kan testas automatiskt utan svaarigheter kan det ibland uppstaa
problem. Det kan vara moejligt att undvika dessa problem genom att anvaenda
expertlaeget.

Foer att starta installationen i expertlaeget skriver du 0fexpert <ENTER>07.

Naer befinner dig i expertlaeget kommer du att ha total kontroll oever
installationen. Du kommer ocksaa att kunna ange valfria modulparametrar naer
du befinner dig i expertlaeget.










05[F1-Huvud] [F2-Allmaen] [F3-Expert] [F4-Kaerna] [F5-Raeddning]07
