

                        09Allmaen uppstartshjaelp07

Du kan starta installationsprogrammet till 0cRed Hat07 Linux och paaboerja
installationen fraan den haer skaermen. I de flesta fall aer det enklaste
saettet att starta att helt enkelt bara trycka 0f<ENTER>07-tangenten.

Vissa haardvarukonfigurationer kan ha problem med den automatiska
haardvarudetekteringen som goers under installationen. Aeven om det aer
ovanligt kan det haenda ibland. Om du har problem med installationen boer du
starta om den och anvaenda expertlaeget. Tryck 05<F3>07 foer mer information
om expertlaeget.

Det finns ett antal parametrar som kan skickas till Linuxkaernan vid
uppstart. Dessa inkluderar dock inte parametrar foer enheter som cdrom-
enheter eller naetverkskort. Tryck 05<F4>07 foer mer information.






05[F1-Huvud] [F2-Allmaen] [F3-Expert] [F4-Kaerna] [F5-Raeddning]07
