

                 09Hjaelp foer parametrar till kaernan07

Vissa parametrar till kaernan kan anges paa kommandoraden och kommer att
skickas till den koerande kaernan. Det haer inkluderar inte flaggor till
moduler som exempelvis naetverkskort eller enheter som exempelvis cdrom-
enheter.

Foer att skicka en flagga till kaernan anvaender du foeljande format:
     0flinux <flaggor>07
Om ett annat installationslaege oenskas anger du det efter flaggorna.

Om du exempelvis vill installera paa ett system med 128 MB RAM-minne genom
att anvaenda expertlaeget skriver du foeljande:
     0flinux mem=128M expert07

Foer att kunna skicka flaggor till moduler maaste du anvaenda expertlaeget
foer att slaa av den automatiska PCI-testningen. Naer installationsprogrammet
fraagar efter vilken enhetstyp som behoever en flagga eller parameter skickad
till den kommer det att finnas en plats att ange dessa daa.


05[F1-Huvud] [F2-Allmaen] [F3-Expert] [F4-Kaerna] [F5-Raeddning]07
