

                     09Hjaelp foer raeddningslaeget07

0cRed Hat07 Linux-cdrom:en har ett raeddningslaege som kan anvaendas daa
systemet inte startar korrekt. Raeddningslaeget innehaaller maanga
anvaendbara verktyg (texteditor, haarddisk- och RAID-verktyg mm.) som goer
det moejligt foer en att reparera ett system till ett fungerande tillstaand.

Foer att gaa in i raeddningslaeget startar du ditt system fraan 0cRed Hat07
Linux-cdrom:en och skriver 0flinux rescue <ENTER>07.












05[F1-Huvud] [F2-Allmaen] [F3-Expert] [F4-Kaerna] [F5-Raeddning]07
