#!/usr/bin/python
#
# scan system for harddrives and output device name/size
#
# Copyright (C) 2007, 2009  Red Hat, Inc.  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import os
import sys
import parted
import _ped

def main(argv):
    lst = set()

    for dev in filter(lambda d: d.type != parted.DEVICE_DM, parted.getAllDevices()):
        if dev.path.startswith("/dev/"):
            path = dev.path[5:]
        else:
            path = dev.path

        lst.add((path, dev.getSize()))

    lst = list(lst)
    lst.sort()
    for dev, size in lst:
        print dev, size

if __name__ == "__main__":
    main(sys.argv)
