#!/usr/bin/python
#
# mknod-stub
#
# Copyright (C) 2007  Red Hat, Inc.  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import stat, string, sys, os
from pyanaconda import isys

def usage():
    sys.stderr.write("Usage: %s <path> [b|c] <major> <minor>\n" %(sys.argv[0],))
    sys.exit(1)

def main():
    if len(sys.argv) < 2:
        usage()

    if (sys.argv[1] == '-h') or (sys.argv[1] == '--help'):
        usage()

    path = sys.argv[1]

    if len(sys.argv) < 5:
        usage()

    if (sys.argv[2] == 'b'):
        type = stat.S_IFBLK
    elif (sys.argv[2] == 'c'):
        type = stat.S_IFCHR
    else:
        usage()

    major = int(sys.argv[3])
    minor = int(sys.argv[4])
    path = sys.argv[1]

    os.mknod(path, 0644 | type, os.makedev(major, minor))

if __name__ == "__main__":
    main()
