# Use this Makefile and the prereqs() function to define any objects that need
# to be built for a particular kickstart test that could be shared by multiple
# tests. The Makefile is run with PWD = .../kickstart_tests/scripts. The
# following environment variables are available:
#
# IMAGE - the boot.iso
# KSTESTDIR - the absolute path to the kickstart_tests directory, sans scripts/
#
# This file is used before gaining root privileges but sudo probably works if
# you need it.

# This is a regular Makefile without any automake weirdness, so just keep it
# friendly.

proxy-common.ks: proxy.py
	@# Wrap the proxy server in a %pre script that writes the server file to
	@# to location in the installer environment and runs it in the background
	@server_py="$$(< proxy.py)"; \
	echo '%pre --erroronfail' > $@
	echo 'cat - << "EOF" > /tmp/proxy-test.py' >> $@
	cat proxy.py >> $@
	echo 'EOF' >> $@
	echo 'python3 /tmp/proxy-test.py > /dev/null 2>&1 &' >> $@
	echo '%end' >> $@
