include ../Makefile.inc

all:

depend:

install:
	install -m 644 screenfont-$(ARCH).gz $(DESTDIR)/$(RUNTIMEDIR)

clean:

i386:
	./updfonts i386

alpha:
	./updfonts alpha

sparc:
	./updfonts sparc

ia64:
	./updfonts ia64
