#!/bin/sh

LANGTABLE=../lang-table

ARCH=$1
if [ -z "$ARCH" ]; then
    echo "usage: $0 <arch>"
    exit 1
fi

fontlist=`awk '{ print $4 }' < $LANGTABLE | grep -v "None" | sort -u`

echo $fontlist

TMPDIR=/tmp/fontdir.$$
rm -rf $TMPDIR

rm -rf $TMPDIR
mkdir -p $TMPDIR

for n in $fontlist; do
    echo -n $n
    map=$(grep $n $LANGTABLE | head -1 | awk '{ print $3 }')

    echo -n " map "
    echo $map

    consolechars --tty /dev/tty1 -f $map -m $n
    ../utils/snarffont > $TMPDIR/$n
done

consolechars --tty /dev/tty1 -d

(cd $TMPDIR > /dev/null; ls * | cpio -o -H crc) | gzip -9 > fonts-$ARCH

rm -rf $TMPDIR
