
 
                09Welcome to 0cRed Hat09 Linux 7.0!07

 o  Pour installer ou mettre à jour un système utilisant
   0cRed Hat07 Linux 3.0.3 ou une version ultérieure en mode graphique,
    appuyez sur la touche 0f<ENTREE>07.

 o  Pour installer ou mettre à jour un système utilisant
   0cRed Hat07 Linux 3.0.3 ou une version ultérieure en mode caractère,
    entrez : 0ftext <ENTREE>07.

 o  Pour activer le mode expert, entrez : 0fexpert <ENTREE>07.
    Appuyez sur 05<F3>07 pour plus d'informations sur le mode expert.

 o  Pour activer le mode de secours, entrez : 0flinux rescue <ENTREE>07.
    Appuyez sur 05<F5>07 pour plus d'informations sur le mode de secours.

 o  Si vous avez une disquette de pilotes, entrez : 0flinux dd <ENTREE>07.

 o  Utilisez les touches de fonction ci-dessous pour plus d'informations.


05[F1-Principal] [F2-Général] [F3-Expert] [F4-Noyau] [F5-Secours]07
