 
                090cRed Hat09 Linux @VERSION@! vous souhaite la bienvenue !07

 - Pour une nouvelle installation, ou pour mettre … jour un systŠme 
   0cRed Hat07 Linux en mode graphique, tapez : 0f<ENTER>07.
 - Pour une nouvelle installation ou pour mettre … jour un systŠme 
   0cRed Hat07 Linux en mode texte, tapez : 0ftext <ENTER>07.
 - Pour activer le mode basse r‚solution, tapez : 0flowres <ENTER>07.  
   Pressez 05<F2>07 pour obtenir des informations sur le mode basse r‚solution
 - Pour d‚sactiver le mode m‚moire vid‚o, tapez : 0fnofb <ENTER>07.  
   Pressez 05<F2>07 pour obtenir des informations sur la d‚sactivation du mode
   m‚moire vid‚o.
 - Pour activer le mode expert, tapez : 0fexpert <ENTER>07.  
   Presser 05<F3>07 pour obtenir des informations sur le mode expert.
 - Pour activer le mode de secours, tapez : 0flinux rescue <ENTER>07.  
   Pressez 05<F5>07 pour obtenir des informations sur ce mode.
 - Pour utiliser une disquette de pilotes, tapez : 0flinux dd <ENTER>07.
 - Utilisez les touches de fonction ci-dessous pour obtenir plus 
   d'informations.




05[F1-Principal] [F2-G‚n‚ral] [F3-Expert] [F4-Noyau] [F5-Secours]07
