

                 090cRed Hat09 Linux 6.2 vous souhaite la bienvenue !07

o  Pour une nouvelle installation, ou pour mettre … jour un systŠme 0cRed Hat07
   Linux 2.0 ou sup‚rieur en mode graphique, tapez 0f<Entr‚e>07.

o  Pour une nouvelle installation, ou pour mettre … jour un systŠme 0cRed Hat07
   Linux 2.0 ou sup‚rieur en mode texte, tapez : 0ftext <Entr‚e>07.

o  Pour activer le mode expert, tapez : 0fexpert <Entr‚e>07. Pressez 05<F3>07 pour
   obtenir des informations sur ce mode.

o  Pour activer le mode de secours, tapez : 0flinux rescue <Entr‚e>07. Pressez
   05<F5>07 pour obtenir des informations sur ce mode.

o  Pour utiliser une disquette de pilotes, tapez : 0flinux dd <Entr‚e>07.

o  Utilisez les touches de fonction ‚num‚r‚es ci-dessous pour obtenir plus 
   d'informations.


05[F1-Principal] [F2-G‚n‚ral] [F3-Expert] [F4-Noyau] [F5-Secours]07
