

                        09Aide sur le mode expert07

L'installation par défaut de 0cRed Hat07 Linux utilise une détection
automatique du matériel de votre système. Bien que la fonction de détection
automatique fonctionne correctement avec la plupart des systèmes, elle peut
entraîner des problèmes dans certains cas. Vous pouvez résoudre ces problèmes
en utilisant le mode expert.

Pour démarrer l'installation à l'aide du mode expert,
entrez 0fexpert <ENTREE>07.

En mode expert, vous contrôlez totalement le processus d'installation. Le
mode expert permet également d'entrer des paramètres de module en option.








05[F1-Principal] [F2-Général] [F3-Expert] [F4-Noyau] [F5-Secours]07

