

                          09Aide sur le mode expert07

La m‚thode d'installation par d‚faut de 0cRed Hat07 Linux effectue une auto-
d‚tection du mat‚riel de votre systŠme. Bien que la plupart des mat‚riels
soient d‚tect‚s correctement, des problŠmes peuvent survenir. Le mode expert
permet de les r‚gler.

Pour lancer l'installation en mode expert, tapez : 0fexpert <Entr‚e>07.

Lorsque vous serez en mode expert, vous aurez le contr“le total du processus
d'installation. Vous pourrez aussi pr‚ciser des paramŠtres optionnels pour 
les modules.








05[F1-Principal] [F2-G‚n‚ral] [F3-Expert] [F4-Noyau] [F5-Secours]07
