
                           09Aide g‚n‚rale07

Vous pouvez lancer le processus d'installation. Dans la plupart des cas,
la meilleure fa‡on de faire est de presser la touche 0f<ENTER>07.

Le programme d'installation graphique utilise une m‚moire vid‚o 16-bit en
r‚solution 800x600. Si vous avez des problŠmes avec le programme d'installation
graphique, essayez l'une des options suivantes :
    -  Lancez le proramme d'installation en r‚solution 640x480 en tapant
       0flowres <ENTER>07.
    -  N'utilisez pas le mode m‚moire vid‚o. Pour cela, tapez : 0fnofb <ENTER>07.
    -  Essayez une autre r‚solution en ajoutant 'vga=xxx' par rapport aux
       valeurs suivantes :
         1024x768x8bpp  -> vga=773        1024x768x16bpp  -> vga=791 
         1280x1024x8bpp -> vga=775        1280x1024x16bpp -> vga=794
Certaines configurations mat‚rielles peuvent avoir des problŠmes avec la 
d‚tection automatique du mat‚riel pendant l'installation. Si vous avez des
problŠmes pendant l'installation, relancez-la en mode expert. Pressez 05<F3>07
pour obtenir des informations sur ce mode.
Voici quelques  paramŠtres pouvant ˆtre pass‚s au noyau Linux au moment du
d‚marrage. Pressez 05<F4>07 pour plus d'information. 

05[F1-Principal] [F2-G‚n‚ral] [F3-Expert] [F4-Noyau] [F5-Secours]07
