

                        09Aide générale au démarrage07

Vous pouvez charger le programme d'installation de 0cRed Hat07 Linux,
puis commencer le processus d'installation à partir de l'invite. Le plus
souvent, la meilleure manière de démarrer consiste simplement à appuyer sur
la touche 0f<ENTREE>07.

Certaines configurations matérielles posent problème lors de la détection
automatique durant l'installation. Bien que ce soit rare, cela peut arriver.
En cas de problème en cours d'installation, redémarrez l'installation en
mode expert. Appuyez sur 05<F3>07 pour plus d'informations sur le mode
expert.

Plusieurs paramètres peuvent être transmis au noyau Linux au démarrage. Ceux-ci
ne comprennent pas les paramètres appropriés pour des périphériques tels que
des unités de CD-ROM ou des cartes ethernet. Appuyez sur 05<F4>07 pour plus
d'informations. 






05[F1-Principal] [F2-Général] [F3-Expert] [F4-Noyau] [F5-Secours]07

