

                             09Aide g‚n‚rale07

Vous pouvez lancer le programme d'installation de 0cRed Hat07 Linux et d‚marrer 
le processus d'installation … partir de l'invite. Dans la plupart des cas,
la meilleure fa‡on de faire est de presser la touche 0f<Entr‚e>07.

Certaines configurations mat‚rielles peuvent avoir des problŠmes avec la 
d‚tection automatique du mat‚riel pendant l'installation. Bien que ce soit 
rare, cela arrive occasionnellement. Si vous avez des problŠmes pendant 
l'installation, relancez-la en mode expert. Pressez 05<F3>07 pour obtenir des
informations sur ce mode.

Un certain nombre de paramŠtres peuvent ˆtre pass‚s au noyau Linux au moment 
du d‚marrage. Cela ne comprend pas les paramŠtres de p‚riph‚riques comme les 
lecteurs de CD-ROM ou les cartes Ethernet. Pressez 05<F4>07 pour plus 
d'information. 




05[F1-Principal] [F2-G‚n‚ral] [F3-Expert] [F4-Noyau] [F5-Secours]07
