00
 

                       09Installer Boot Options07

 -  To disable hardware probing, type: linux noprobe <ENTER>.  

 -  To test the install media you are using, type: linux mediacheck <ENTER>.  

 -  To enable rescue mode, type: linux rescue <ENTER>.  
    Press <F4> for more information about rescue mode.

 -  If you have a driver disk, type: linux dd <ENTER>.

 -  To prompt for the install method being used on a CD-ROM install, 
    type linux askmethod <ENTER>.

 -  If you have an installer update disk, type: linux updates <ENTER>.

02[F1-Main] [F2-Options] [F3-General] [F4-Kernel] [F5-Rescue]07
