

                       09Mode Secours de 0cRed Hat07

Le programme d'installation de 0cRed Hat07 comprend un mode de secours qui peut
ˆtre utilis‚ lorsque votre systŠme ne d‚marre pas correctement. Ce mode donne
accŠs … de nombreux utilitaires (‚diteur de texte, outils disques durs et RAID,
etc.) qui doivent permettre de rendre … nouveau le systŠme op‚rationnel.

Pour acc‚der au mode de secours, d‚marrez votre systŠme depuis le CDROM 0cRed Hat07
et tapez : 0flinux rescue <Entr‚e>07.











05[F1-Principal] [F2-G‚n‚ral] [F3-Expert] [F4-Noyau] [F5-Secours]07
