

                        09Aide sur le mode de secours07

Le CD-ROM 0cRed Hat07 Linux comprend un mode de secours qui peut être
utilisé lorsqu'un système ne démarre pas correctement. Le mode de secours
comprend de nombreux utilitaires pratiques (éditeur, disque dur, outils RAID,
etc.) qui permettent de restaurer un système en état de fonctionnement.

Pour entrer en mode de secours, démarrez le système à partir du
CD-ROM 0cRed Hat07 Linux et entrez 0flinux rescue <ENTREE>07.












05[F1-Principal] [F2-Général] [F3-Expert] [F4-Noyau] [F5-Secours]07

