 
                09Willkommen zu 0cRed Hat09 Linux @VERSION@!07

 -  Drcken Sie 0f<EINGABETASTE>07, um 0cRed Hat07 Linux im Grafikmodus
    zu installieren.
 -  Um eine textbasierte Installation oder Aktualisierung von 0cRed Hat07
    Linux vorzunehmen, geben Sie 0ftext <EINGABETASTE>07 ein.
 -  Um den Modus mit niedriger Aufl”sung zu aktivieren, geben Sie 
    0flowres <EINGABETASTE>07 ein. Drcken Sie 05<F2>07, um weitere
    Informationen zu erhalten.
 -  Um den Framebuffer-Modus auszuschalten, geben Sie 0fnofb <EINGABETASTE>07 ein.
    Drcken Sie 05<F2>07, um weitere Informationen ber das Ausschalten des
    Framebuffer-Modus zu erhalten.
 -  Um den Expertenmodus zu aktivieren, geben Sie 0fexpert <EINGABETASTE>07 ein.
    Drcken Sie 05<F5>07, um weitere Informationen ber den Expertenmodus zu 
    erhalten.
 -  Um den Rettungsmodus zu aktivieren, geben Sie 0flinux rescue <EINGABETASTE>07
    ein.Drcken Sie 05<F5>07, um weitere Informationen ber den Rettungsmodus 
    zu erhalten.
 -  Wenn Sie eine Treiberdiskette haben, geben Sie 0flinux dd <EINGABETASTE>07 ein.
 -  Durch Drcken der unten aufgefhrten Funktionstasten erhalten Sie
    weitere Informationen.

05[F1-Hauptbildschirm] [F2-Allgemein] [F3-Expertenmodus] [F4-Kernel] [F5-Rettung]07
