
 
              09Willkommen bei 0cRed Hat09 Linux 6.9!07

 o  Um eine grafische Installation oder Aktualisierung auf einem System
    vorzunehmen, auf dem 0cRed Hat07 Linux 2.0 oder sp„ter ausgefhrt
    wird, drcken Sie die 0f<EINGABETASTE>07.
 o  Um eine textbasierte Installation oder Aktualisierung auf einem System
    vorzunehmen, auf dem 0cRed Hat07 Linux 2.0 oder sp„ter ausgefhrt
    wird, geben Sie Folgendes ein: 0ftext <EINGABETASTE>07.
 o  Um den Expertenmodus zu aktivieren, geben Sie ein:
0fexpert <EINGABETASTE>07.  Drcken Sie 05<F3>07, um weitere
    Informationen ber den Expertenmodus zu erhalten.
 o  Um den Rettungsmodus zu aktivieren, geben Sie ein:
0flinux rescue <EINGABETASTE>07.  Drcken Sie 05<F5>07
    fr weitere Informationen ber den Rettungsmodus.
 o  Wenn Sie ber eine Treiberdiskette verfgen, geben Sie ein:
0flinux dd <EINGABETASTE>07.
 o  Durch Drcken der unten aufgefhrten Funktionstasten erhalten Sie
    weitere Informationen.



05[F1-Hauptbildschirm] [F2-Allgemein] [F3-Expertenmodus] [F4-Kernel] [F5-Rettung]07

