

               09Wilkommen bei 0cRed Hat09 Linux 6.2!07

 o  Um ein neues System im Grafikmodus zu installieren oder ein System,
    auf dem 0cRed Hat07 Linux 2.0 oder h”her l„uft, im Grafikmodus
    zu aktualisieren, drcken Sie die 0f<ENTER>07-Taste.

 o  Um ein System zu im Textmodus zu installieren oder ein System, auf dem
    0cRed Hat07 Linux 2.0 oder h”her l„uft, im Textmodus zu aktualisieren,
    geben Sie 0ftext <ENTER>07 ein.

 o  Um den Expertenmodus zu verwenden, geben Sie 0fexpert <ENTER>07 ein.
    Drcken Sie 05<F3>07 fr mehr Informationen zum Expertenmodus.

 o  Um den Rettungsmodus zu verwenden, geben Sie 0frescue <ENTER>07 ein.
    Drcken Sie 05<F5>07 fr mehr Informationen zum Rettungsmodus.

 o  Wenn Sie eine Treiberdiskette haben, geben Sie 0flinux dd <ENTER>07 ein.

 o  Benutzen Sie die unten aufgefhrten Funktionstasten, um mehr Informationen
    zu erhalten.

05[F1-Hauptmen] [F2-Generelles] [F3-Experten] [F4-Kernel] [F5-Rettung]07
