

                   09Hilfe zum Expertenmodus07

Die Standardinstallation von 0cRed Hat07 Linux versucht automatisch
die Hardware Ihres Systems zu erkennen. Obwohl das auf den meisten Systemen
funktioniert, kann es bei bestimmten Konfigurationen zu Problemem kommen.
Man kann diese Probleme mit dem Expertenmodus umgehen.

Um die Installation im Expertenmodus zu starten, geben Sie 0fexpert <ENTER>07
ein.

Im Expertenmodus haben Sie die vollst„ndige Kontrolle ber den 
Installationsprozess. Sie k”nnen dann auch optionale Parameter fr 
Module angeben.








05[F1-Hauptmen] [F2-Generelles] [F3-Experten] [F4-Kernel] [F5-Rettung]07
