

                        09Hilfe zum Expertenmodus07

Bei der standardm„áigen Installation von 0cRed Hat07 Linux wird die
automatische Hardware-Erkennung fr die Konfiguration Ihres Systems verwendet.
Obwohl die meisten Hardware-Komponenten zuverl„ssig erkannt werden, k”nnen in
manchen F„llen Probleme mit dieser Funktion auftreten. Diese Probleme k”nnen
durch die Verwendung des Expertenmodus behoben werden.

Um die Installation im Expertenmodus zu starten, geben Sie
0fexpert <EINGABETASTE>07 ein.

Im Expertenmodus k”nnen Sie alle Abl„ufe beim gesamten Installationsvorgang
kontrollieren und beeinflussen. Darber hinaus k”nnen Sie im Expertenmodus
optionale Modulparameter eingeben.







05[F1-Hauptbildschirm] [F2-Allgemein] [F3-Expertenmodus] [F4-Kernel] [F5-Rettung]07
