

                   09Generelle Hilfe zum Booten07

Sie k”nnen das 0cRed Hat07 Linux-Installationsprogramm von dieser
Eingabeaufforderung aus laden, und die Installation beginnen.  In den
meisten F„llen ist es der beste Weg, einfach die 0f<ENTER>07-Taste
zu drcken.

Manche Hardwarekonfigurationen k”nnen w„hrend der Installation Probleme mit
der automatischen Hardwareerkennung verursachen. Das ist selten, aber kommt
gelegentlich vor. Falls Sie w„hrend der Installation Probleme haben,
starten Sie die Installation im Expertenmodus neu. Drcken Sie 05<F3>07
fr mehr Informationen zum Expertenmodus.

Es gibt viele Parameter, die dem Linux-Kernel beim Booten bergeben werden
k”nnen. Parameter fr Ger„te wie CD-ROM-Laufwerke oder Ethernet-Karten
geh”ren nicht dazu.
Drcken Sie 05<F4>07 fr mehr Informationen.




05[F1-Hauptmen] [F2-Generelles] [F3-Experten] [F4-Kernel] [F5-Rettung]07
