

                        09Allgemeine Hilfe zum Booten07

Sie k”nnen das 0cRed Hat07 Linux Installationsprogramm von diesem Prompt
aus laden und mit der Installation beginnen. In den meisten F„llen mssen
Sie zum Starten lediglich die 0f<EINGABETASTE>07 drcken.

Bei bestimmten Hardware-Konfigurationen k”nnen mit der automatischen Hardware-
Erkennung bei der Installation Probleme auftreten. Dies ist zwar selten, kann
aber mitunter vorkommen. Wenn Sie bei der Installation Probleme feststellen,
mssen Sie die Installation im Expertenmodus neu starten. Drcken Sie 05<F3>07
fr weitere Informationen ber den Expertenmodus.

Beim Booten kann eine ganze Reihe von Parametern an den Linux-Kernel bergeben
werden. Dazu z„hlen allerdings nicht Parameter fr Ger„te wie CD-ROM-Laufwerke
oder Ethernet-Karten. Drcken Sie 05<F4>07 fr weitere Informationen. 






05[F1-Hauptbildschirm] [F2-Allgemein] [F3-Expertenmodus] [F4-Kernel] [F5-Rettung]07
