
                        09Allgemeine Hilfe zum Booten07

Sie k”nnen jetzt mit der Installation beginnen. In den meisten F„llen 
mssen Sie zum Starten lediglich die 0f<EINGABETASTE>07 drcken.
Der grafische Installer startet im Framebuffer-Modus bei 800x600 und 16
Bit-Farbtiefe. Bei Problemen mit den grafischen Installer, probieren 
Sie folgenden Optionen:
    -  640x480 verwenden: Geben Sie 0flowres <EINGABETASTE>07 ein.
    -  Kein Framebuffer-Modus: Geben Sie 0fnofb <EINGABETASTE>07 ein.
    -  Andere Aufl”sungen verwenden: Geben Sie 'vga=xxx' ein, und zwar fr
          1024x768x8bpp  -> vga=773        1024x768x16bpp  -> vga=791 
          1280x1024x8bpp -> vga=775        1280x1024x16bpp -> vga=794    
Bei bestimmten Hardware-Konfigurationen k”nnen in seltenen F„llen Probleme
mit der automatischen Hardware-Erkennung w„hrend der Installation auftreten. 
Wenn Sie Probleme feststellen, mssen Sie die Installation im Expertenmodus 
neu starten. Weitere Informationen zum Expertenmodus erhalten Sie mit 05<F3>07.
Beim Booten k”nnen eine ganze Reihe von Parametern an den Linux-Kernel 
bergeben werden. 
Dazu z„hlen allerdings nicht Parameter fr Ger„te wie CD-ROM-Laufwerke oder 
Ethernet-Karten. Drcken Sie 05<F4>07 fr weitere Informationen zur
Parameterbergabe.

05[F1-Hauptbildschirm] [F2-Allgemein] [F3-Expertmodus] [F4-Kernel] [F5-Rettung]07
