

                        09Hilfe zum Rettungsmodus07

Die 0cRed Hat07 Linux CD-ROM stellt Ihnen einen Rettungsmodus zur Verfgung,
der dann verwendet werden sollte, wenn Ihr System nicht richtig bootet. Der
Rettungsmodus stellt Ihnen viele ntzliche Dienstprogramme zur Verfgung
(Editor, Tools fr Festplatte und RAID-Ger„te usw.), mit denen Sie Ihr System
wieder in einen funktionierenden Zustand versetzen k”nnen.

Um den Rettungsmodus aufzurufen, booten Sie Ihr System von der
0cRed Hat07 Linux CD-ROM und geben 0flinux rescue <EINGABETASTE>07 ein.











05[F1-Hauptbildschirm] [F2-Allgemein] [F3-Expertenmodus] [F4-Kernel] [F5-Rettung]07
