

                      09Hilfe zum Rettungsmodus07

Die 0cRed Hat07 Linux CD-ROM beinhaltet einen Rettungsmodus, welcher 
benutzt werden kann, wenn das System nicht mehr ordentlich hochfährt
Der Rettungsmodus enthält viele nützliche Dienstprogramme (Editor, Festplatten
und Raid Tools, etc.), die Ihnen erlauben das System wieder in einen 
arbeitsfähigen Zustand zu versetzen.

Um den Rettungsmodus zu aktivieren, booten Sie Ihr System von der 
0cRed Hat07 Linux CDROM und geben Sie 0flinux rescue <ENTER>07 ein.











05[F1-Hauptmen] [F2-Generelles] [F3-Experten] [F4-Kernel] [F5-Rettung]07
