from translate import N_

INSTALL_OK = 0
INSTALL_BACK = -1
INSTALL_NOOP = -2

TEXT_OK_STR = N_("Ok")
TEXT_OK_CHECK  = "ok"
TEXT_OK_BUTTON = (TEXT_OK_STR, TEXT_OK_CHECK)

TEXT_CANCEL_STR = N_("Cancel")
TEXT_CANCEL_CHECK  = "cancel"
TEXT_CANCEL_BUTTON = (TEXT_CANCEL_STR, TEXT_CANCEL_CHECK)

TEXT_BACK_STR = N_("Back")
TEXT_BACK_CHECK = "back"
TEXT_BACK_BUTTON = (TEXT_BACK_STR, TEXT_BACK_CHECK)

TEXT_F12_CHECK = "F12"


TRUE = 1
FALSE = 0
