include ../Makefile.inc

all:
	@echo "nothing to do"

install: 
	mkdir -p $(DESTDIR)/$(ANACONDADATADIR)/pixmaps
	install *.png $(DESTDIR)/$(ANACONDADATADIR)/pixmaps

	mkdir -p $(DESTDIR)/$(ANACONDADATADIR)/pixmaps/comps
	install comps/*.png $(DESTDIR)/$(ANACONDADATADIR)/pixmaps/comps

depend:

clean:
