#!/bin/sh

# This is the expected entry point for Cockpit CI;

set -eu

# Create the SRPM in the Cockpit container.
echo "DEBUG: Creating SRPM ..."
./autogen.sh && ./configure && make srpm

# Build the RPM in a mock environment to get the right Python version.
echo "DEBUG: Creating RPM ..."
mock -r fedora-rawhide-x86_64 --resultdir=./result/build/01-rpm-build ./result/build/00-srpm-build/anaconda-*.src.rpm

# Run the Web UI tests.
echo "DEBUG: Running tests ..."
make webui-tests
