#!/usr/bin/perl

foreach $n (@ARGV) {
    $n =~ s/\.o$//;
    $mods{"\"$n\""} = $n;
}

while (<STDIN>) {
    chop;
    @a = split;
    if ($mods{$a[2]}) {
	print "$_\n";
    } elsif ($_ =~ /Card:Intel.*81[05]/) {
	print "$_\n";
    }
}
