#!/usr/bin/perl

open (F, $ARGV[0]);
@ents = (<F>);
close (F);

shift @ARGV;

foreach $n (@ARGV) {
    $n =~ s/\.o$//;
    $mods{"$n"} = $n;
}


while (<STDIN>) {
    chop;
    $line = $_;
    s/0x0000/0x/g;
    @a = split;
    if ($mods{$a[0]}) {
	if ($a[1] ne "0xffffffff" && $a[2] ne "0xffffffff") {
	    if ($a[3] eq "0xffffffff" && $a[4] eq "0xffffffff") {
	        @res = grep (/^$a[1]\t$a[2]\t"$a[0]"/, @ents);
		if (length(@res) != 0 && ! $res[0]) {
		    print $line."\n";
		}
	    } else {
	        @res = grep (/^$a[1]\t$a[2]\t"$a[0]"/, @ents);
		if ($res[0]) {
		    @b = split "\t",$res[0];
		    if ($b[2] ne "\"$a[0]\"") {
			print $line."\n";
		    }
		} else {
	            @res = grep (/^$a[1]\t$a[2]\t$a[3]\t$a[4]\t"$a[0]"/, @ents);
		    if (!$res[0]) {
			print $line."\n";
		    }
		}
	    }
	}
    }
}
