#!/bin/ksh
# Red Hat Linux S390 installer
#
# Copyright (C) 2000,2001 Red Hat Inc.  
#       David Sainty <dsainty@redhat.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

if [ "$#" = "0" -o  "$1" != "-gui" ]; then
  unset DISPLAY
fi

mv /usr/lib /usr/lib_rd 2>/dev/null
ln -sf /mnt/runtime/usr/lib /usr/lib

# Source the loader configuration
. /tmp/install.cfg

# Copied from rhsetup to correctly write modules.conf
# Options for kernel network drivers.
if [ -n "$LCS" ]; then
  echo "alias $DEVICE lcs"   >> /tmp/modules.conf
fi
if [ -n "$QETH" ]; then
  echo "alias eth0 qeth"    >> /tmp/modules.conf
fi
if [ -n "$HSI" ]; then
  echo "alias hsi0 qeth"    >> /tmp/modules.conf
fi
if [ -n "$IUCV" ]; then
  echo "alias $DEVICE netiucv" >> /tmp/modules.conf
  echo "options netiucv $IUCV" >> /tmp/modules.conf
fi

/sbin/loaderbin

for file in `cat /proc/mounts | /bin/grep '/mnt/sysimage' |
/bin/awk 'BEGIN { FS=" " }
{ print length($2), $2 }' $* |
/bin/sort -n -r |
/bin/sed 's/^[0-9][0-9]* //'`
do
  /bin/umount $file
done

