#!/bin/bash

if [ ! -d $1/RedHat/RPMS ]; then
    echo $1 is not a Red Hat image >&2
    exit 1
fi

p=`cd $1; /bin/pwd`

BUILDINSTDIR=$p/buildinstall.tree.$$

rm -rf $BUILDINSTDIR
mkdir -p $BUILDINSTDIR

UPD_INSTROOT=./upd-instroot
MK_IMAGES=./mk-images

BUILDARCH=`rpm -qp --qf "%{ARCH}" $p/RedHat/RPMS/anaconda-runtime-[0-9]*`

if [ ! -f $UPD_INSTROOT ]; then
    cd $BUILDINSTDIR
    rpm2cpio $p/RedHat/RPMS/anaconda-runtime-[0-9]* | cpio --quiet -iumd usr/lib/anaconda-runtime/upd-instroot
    mv usr/lib/anaconda-runtime/upd-instroot .
    rm -rf usr
else
    cp -a $UPD_INSTROOT $BUILDINSTDIR/upd-instroot
fi
UPD_INSTROOT=$BUILDINSTDIR/upd-instroot

if [ ! -f $MK_IMAGES ]; then
    cd $BUILDINSTDIR
    rpm2cpio $p/RedHat/RPMS/anaconda-runtime-[0-9]* | cpio --quiet -iumd usr/lib/anaconda-runtime/mk-images*
    mv usr/lib/anaconda-runtime/mk-images* .
    rm -rf usr
else
    cp $MK_IMAGES* $BUILDINSTDIR/
fi
MK_IMAGES=$BUILDINSTDIR/mk-images

echo "Building images..."
$UPD_INSTROOT $p/RedHat/RPMS $p/image-template $p/RedHat/instimage $BUILDARCH
if [ -x /usr/bin/runroot ]; then
    runroot dist-7.0 --arch $BUILDARCH "cd $BUILDINSTDIR\; $MK_IMAGES $p/RedHat/RPMS $p $p/image-template $BUILDARCH" | tail +2
else
    $MK_IMAGES $p/RedHat/RPMS $p $p/image-template $BUILDARCH
fi

rm -rf $BUILDINSTDIR
rm -rf $p/image-template $p/RedHat/instimage/usr/lib/anaconda-runtime
