#!/usr/bin/perl

# This table is used to eliminate things like French (France)
$defaultTerritory{"Albanian"} = "Albania";
$defaultTerritory{"Belarusian"} = "Belarus";
$defaultTerritory{"Bulgarian"} = "Bulgaria";
$defaultTerritory{"Croatian"} = "Croatia";
$defaultTerritory{"Czech"} = "Czech Republic";
$defaultTerritory{"Danish"} = "Denmark";
$defaultTerritory{"Estonian"} = "Estonia";
$defaultTerritory{"Finnish"} = "Finland";
$defaultTerritory{"French"} = "France";
$defaultTerritory{"German"} = "Germany";
$defaultTerritory{"Greek"} = "Greece";
$defaultTerritory{"Hungarian"} = "Hungary";
$defaultTerritory{"Icelandic"} = "Iceland";
$defaultTerritory{"Indonesian"} = "Indonesia";
$defaultTerritory{"Italian"} = "Italy";
$defaultTerritory{"Irish"} = "Ireland";
$defaultTerritory{"Japanese"} = "Japan";
$defaultTerritory{"Lithuanian"} = "Lithuania";
$defaultTerritory{"Macedonian"} = "Macedonia";
$defaultTerritory{"Norwegian"} = "Norway";
$defaultTerritory{"Polish"} = "Poland";
$defaultTerritory{"Portuguese"} = "Portugal";
$defaultTerritory{"Romanian"} = "Romania";
$defaultTerritory{"Russian"} = "Russia";
$defaultTerritory{"Slovak"} = "Slovak";
$defaultTerritory{"Slovenian"} = "Slovenian";
$defaultTerritory{"Ukrainian"} = "Ukraine";
$defaultTerritory{"Vietnamese"} = "Vietnam";
$defaultTerritory{"Spanish"} = "Spain";
$defaultTerritory{"Swedish"} = "Sweden";
$defaultTerritory{"Turkish"} = "Turkey";
$defaultTerritory{"Thai"} = "Thailand";

$charMap{"EUC-JP"} =  "iso01";
$charMap{"EUC-TW"} =  "iso01";
$charMap{"EUC-KR"} =  "iso01";
$charMap{"GB2312"} =  "iso01";
$charMap{"BIG5"} =  "iso01";
$charMap{"KOI8-U"} =  "koi8-u";
$charMap{"KOI8-R"} =  "koi8-u";
$charMap{"ISO-8859-1"} =  "iso01";
$charMap{"ISO-8859-2"} =  "iso02";
$charMap{"ISO-8859-3"} =  "iso03";
$charMap{"ISO-8859-5"} =  "iso05";
$charMap{"ISO-8859-6"} =  "iso06";
$charMap{"ISO-8859-7"} =  "iso07";
$charMap{"ISO-8859-8"} =  "iso08";
$charMap{"ISO-8859-9"} =  "iso09";
$charMap{"ISO-8859-15"} =  "iso15";

$charFont{"EUC-JP"} =  "lat0-16";
$charFont{"EUC-TW"} =  "lat0-16";
$charFont{"EUC-KR"} =  "lat0-16";
$charFont{"GB2312"} =  "lat0-16";
$charFont{"BIG5"} =  "lat0-16";
$charFont{"KOI8-U"} =  "cyr-sun16";
$charFont{"KOI8-R"} =  "cyr-sun16";
$charFont{"ISO-8859-1"} =  "lat0-sun16";
$charFont{"ISO-8859-2"} =  "lat2-sun16";
#$charFont{"ISO-8859-3"} =  "iso03";		mk_MK -- no font available
$charFont{"ISO-8859-5"} =  "cyr-sun16";
$charFont{"ISO-8859-6"} =  "LatArCyrHeb-16";
$charFont{"ISO-8859-7"} =  "gr.f16";
$charFont{"ISO-8859-8"} =  "LatArCyrHeb-16";
$charFont{"ISO-8859-9"} =  "lat5-sun16";
$charFont{"ISO-8859-15"} =  "lat0-sun16";


open(FILE, "locale -a|");

while (<FILE>) {
#for (['he_IL', 'en_US']) {
    chop;

    # limit to items of the form xx_.*
    /^[a-zA-Z][a-zA-Z]_/ || next;

    $lang=$_;
    $lang =~ s/eucjp/eucJP/;

    open(INFO, "LANG=$lang locale -c language -c territory -k charmap|");
    <INFO>;
    $name = <INFO>;
    <INFO>;
    $territory = <INFO>;
    <INFO>;
    $charmap = <INFO>;
    close(INFO);

    chop $name;
    $name =~ s/^[^"]+"//;
    $name =~ s/"$//;
    chop $territory;
    $territory =~ s/^[^"]+"//;
    $territory =~ s/"$//;
    chop $charmap;
    $charmap =~ s/^[^"]+"//;
    $charmap =~ s/"$//;

    # Some languages name's are the same as their ISO id's!
    ($name eq substr($lang, 0, 2)) && next;

    if ($defaultTerritory{$name} eq "$territory") {
	$fullName = $name;
    } else {
	$fullName = "$name ($territory)";
    }

    $langList{$lang} = $fullName;
    $charmapList{$lang} = $charmap;
}

close(FILE);

for $key (keys %langList) {
    $langName = $langList{$key};
    if ($nameList{$langName}) {
	# we have a conflict. longest wins
	if (length($key) > length($nameList{$langName})) {
	    $nameList{$langName} = $key;
	} else {
	}
    } else {
	$nameList{$langName} = $key;
    }
}

@names = sort(keys %nameList);

for $name (@names) {
    $short = $nameList{$name};
    $map = $charmapList{$short};
    if ($charMap{$map} and $charFont{$map}) {
	print "$short $charMap{$map} $charFont{$map} $name\n";
    }
}

