#!/bin/sh

ARCH=$1
if [ -z "$ARCH" ]; then
    echo "usage: $0 <arch>"
    exit 1
fi

OUTPUT=$2
if [ -z "$OUTPUT" ]; then
    echo "No output specified, using /tmp/keymaps-$ARCH.$$"
    OUTPUT=/tmp/keymaps-$ARCH.$$
fi

TMPDIR=/tmp/keymaps.$$
TOPDIR=`pwd`

rm -rf $TMPDIR
mkdir -p $TMPDIR

if [ $ARCH = "sparc" ]; then
    PATTERN={i386,sun}
else
    PATTERN=i386
fi

MAPS=$(python -c "import rhpl.keyboard_models ; rhpl.keyboard_models.get_supported_models()")

for map in $MAPS ; do 
 eval find /lib/kbd/keymaps/$PATTERN -name "$map.map*" | while read n; do
    /bin/loadkeys `basename $n .gz`
    ../utils/readmap $TMPDIR/`basename $n .map.gz`.map
  done
done

loadkeys us

rm -f $TMPDIR/defkeymap* $TMPDIR/ANSI* $TMPDIR/lt.map

(cd $TMPDIR; $TOPDIR/../utils/mapshdr *.map) > $TMPDIR/hdr
cat $TMPDIR/hdr $TMPDIR/*.map | gzip -9 > $OUTPUT
rm -rf $TMPDIR
