#!/bin/bash
#
# Helper script for updating the Sphinx documentation. It requires a full install of the
# dependencies so we do that in a mock chroot.
#
# Copyright (C) 2015  Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
MOCKCFG=fedora-rawhide-x86_64

if [ -z "$DISPLAY" ]; then
    echo "Run script on a desktop system with a GUI"
    exit 1
fi
# Pass the script anything to skip re-initializing the chroot
[ -z "$1" ] && mock -r $MOCKCFG --init
mock -r $MOCKCFG -i anaconda-gui -i python3-sphinx -i python3-sphinx_rtd_theme -i ostree -i graphviz
# modules needed to document tests
mock -r $MOCKCFG -i python3-mock -i python3-rpmfluff -i python3-lxml -i python3-polib -i python3-pocketlint
mock -r $MOCKCFG --copyin $PWD /builddir/anaconda/
# Note that DISPLAY is needed to make GTK happy, so this needs to be run from a system with a GUI
mock -r $MOCKCFG --chroot "cd /builddir/anaconda/docs/; DISPLAY=$DISPLAY make -f Makefile.am html"
mock -r $MOCKCFG --copyout /builddir/anaconda/docs/html $PWD/docs/html.new

echo "Now make sure the ./docs/html.new/ looks ok and copy it over the top of ./docs/html/ and commit."
echo "Then copy ./docs/html/ outside the repo and check out the gh-pages branch. Copy them back to /"
echo "and commit to update the https://rhinstaller.github.io/anaconda/ page."
