#! /bin/bash
#
# restart-anaconda: Debugging tool to restart stage2 Anaconda.
#
# Copyright (C) 2010
# Red Hat, Inc.  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

rm -rf /tmp/updates || echo "Error removing /tmp/updates. Updates won't be re-downloaded." >&2

if [[ -f /var/run/iscsid.pid ]]; then
    # iscsid must die else it will cause us troubles on the next run
    # log out of all nodes
    /sbin/iscsiadm -m node --logoutall=all
fi

# This will kill all programs in the anaconda group and restart the
# service.
systemctl stop anaconda.service
anaconda-cleanup
systemctl start --no-block anaconda.service
