#!/bin/bash
#
# scrubtree
#
# Copyright (C) 2007  Red Hat, Inc.  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

DEBUG=""

if [ "$1" == "--debug" ]; then
    DEBUG="--debug"
    shift
fi

if [ -z "$1" ]; then
    echo "Usage: $0 /path/to/tree"
    exit 1
fi

p=$1

ARCH=`uname -m | sed -e 's/i.86/i386/'`

if [ $ARCH = x86_64 -o $ARCH = s390x -o $ARCH = ppc64 ]; then
    LIBDIR=lib64
else
    LIBDIR=lib
fi

# Must create ld.so.conf, because ldconfig does not cache
# dirs specified on the command line.
touch $p/etc/ld.so.conf
mkdir $p/proc
mount -t proc proc $p/proc
echo /usr/kerberos/$LIBDIR > $p/etc/ld.so.conf
(cd $p; /usr/sbin/chroot $p usr/sbin/ldconfig )

if [ $ARCH != s390 -a $ARCH != s390x ]; then
    rm -f $p/usr/sbin/ldconfig 
fi
rm $p/etc/ld.so.conf

umount $p/proc
