#!/bin/bash

if [ ! -f $1 ]; then
    echo "$1 doesn't exist"
    exit 1
fi

MNTPOINT=/tmp/updboottree.$$
INITRD=/tmp/updboottree.$$.initrd
LOOPMNT=/tmp/updboottree.$$.initrdmnt

rm -rf $MNTPOINT $LOOPMNT
mkdir $MNTPOINT $LOOPMNT
mount -o loop $1 $MNTPOINT

gunzip < $MNTPOINT/initrd.img > $INITRD

mount -o loop $INITRD $LOOPMNT

FROM=$2
TO=$FROM
if [ $(echo $FROM | cut -d- -f1) = loader ]; then
    TO=loader
fi

if [ ! -x $LOOPMNT/sbin/$TO ]; then
    echo "$LOOPMNT/sbin/$TO doesn't exist"
else
    install -s $FROM $LOOPMNT/sbin/$TO
fi

umount $LOOPMNT
gzip -9 < $INITRD > $MNTPOINT/initrd.img
umount $MNTPOINT

rm -rf $MNTPOINT $LOOPMNT $INITRD
