#!/bin/sh
set -eux

# Avoid clobbering the host's checkout, so work from a copy
cp -r /anaconda /tmp/
cd /tmp/anaconda
rm -rf test-logs

./autogen.sh
./configure
make

# always copy the results back to the host
copy_logs() {
    mkdir -p /anaconda/test-logs/
    # clean up from previous run
    rm -rf /anaconda/test-logs/*
    find -name '*.log' -exec cp '{}' /anaconda/test-logs/ \;
}
trap copy_logs EXIT INT QUIT PIPE

if [ $1 == "--build-rpms" ]; then
    make rpms
    dnf install -y result/build/01-rpm-build/*.rpm
    shift 1
fi

# run user-supplied command (by default, `make ci`)
$@
