#!/bin/bash
#
# Build Anaconda package from the current working directory repository and build a boot.
# iso by lorax. The boot.iso will be stored in `/images/` directory.
#
# Input directory:
# /anaconda (Anaconda repository with RO access)
#
# Output directory:
# /images (Where the boot.iso will be stored)
#

set -eux
# /anaconda from host should be read-only, build in a copy
cp -a /anaconda/ /tmp/
cd /tmp/anaconda

# build RPMs and repo for it; bump version so that it's higher than rawhide's
echo "::group::Build Anaconda RPMs and make a repository"
sed -ri '/AC_INIT/ s/\[[0-9.]+\]/[999999999]/' configure.ac
./autogen.sh
./configure
make rpms
createrepo_c result/build/01-rpm-build/
echo "::endgroup::"

# build boot.iso with our rpms
echo "::group::Build boot.iso with the RPMs"
. /etc/os-release
MAJOR_VERSION=${VERSION_ID%%.*}
MINOR_VERSION=${VERSION_ID#*.}
# The --volid argument can cause different network interface naming: https://github.com/rhinstaller/kickstart-tests/issues/448
lorax -p RHEL -v $MAJOR_VERSION -r $MINOR_VERSION --volid RHEL-$MAJOR_VERSION-$MINOR_VERSION-0-BaseOS-x86_64 \
      --nomacboot \
      -s http://download.devel.redhat.com/rhel-9/nightly/RHEL-9-Beta/latest-RHEL-9/compose/BaseOS/x86_64/os/ \
      -s http://download.devel.redhat.com/rhel-9/nightly/RHEL-9-Beta/latest-RHEL-9/compose/AppStream/x86_64/os/ \
      -s file://$PWD/result/build/01-rpm-build/ \
      $@ \
      lorax

cp lorax/images/boot.iso /images/
echo "::endgroup::"
