

                 09Welcome to 0cRed Hat09 Linux 6.2!07

 o  Per installare o aggiornare un sistema con 0cRed Hat07 Linux 2.0 
    o piu' recente in modalita' grafica, premete il tasto 0f<ENTER>07.

 o  Per installare o aggiornare un sistema con 0cRed Hat07 Linux 2.0 
    o piu' recente in modalita' testo, digitate 0ftext <ENTER>07.

 o  Per attivare l'expert mode, digitate: 0fexpert <ENTER>07.  Premete 05<F3>07 
    per ricevere piu' informazioni riguardanti l'expert mode.

 o  Per attivare il rescue mode, digitate: 0frescue <ENTER>07.  Premete 05<F5>07 
    per ricevere piu' informazioni riguardanti il rescue mode.

 o  Se avete un disco driver, digitate: 0flinux dd <ENTER>07.

  Premete i tasti funzione visualizzati in fondo allo schermo per
  ricevere piu' informazioni.



05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07
