 
                09Benvenuti in 0cRed Hat09 Linux @VERSION@!07


 -  Per installare o aggiornare 0cRed Hat07 Linux in modalita' grafica, 
    premete il tasto 0f<ENTER>07.
 -  Per installare o aggiornare 0cRed Hat07 Linux in modalita' testo,
    digitate: 0ftext <ENTER>07.
 -  Per attivare la modalita' bassa risoluzione, digitate: 0flowres <ENTER>07.  
    Premete 05<F2>07 per maggiori informazioni su tale modalita'.
 -  Per disattivare la modalita' framebuffer, digitate: 0fnofb <ENTER>07.  
    Premete 05<F2>07 per maggiori informazioni sulla disattivazione
    della modalita' framebuffer.
 -  Per attivare la modalita' expert, digitate: 0fexpert <ENTER>07.  
    Premete 05<F3>07 per maggiori informazioni su tale modalita'.
 -  Per attivare la modalita' rescue, digitate: 0flinux rescue <ENTER>07.  
    Premete 05<F5>07 per maggiori informazioni su tale modalita'.
 -  Se avete un dischetto dei driver, digitate: 0flinux dd <ENTER>07.
 -  Usate i tasti funzione riportati sotto per ottenere maggiori informazioni.




05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07
