

                        09Expert Mode Help07

L'installazione di default di 0cRed Hat07 Linux usa l'autoprobing per
riconoscere automaticamente l'hardware del sistema. Sebbene la maggior 
parte dell'hardware viene riconosciuto senza difficolta', in certi casi ci 
possono essere dei problemi. E' possibile risolvere questi problemi usando
l'expert mode.

Per attivare l'installazione in expert mode, digitate 0fexpert <ENTER>07.

In expert mode, avrete il completo controllo del processo di installazione.
Percio' dovrete essere in grado di inserire i parametri opzionali dei moduli.









05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07
