

                        09Modalita' expert - Help07

Il metodo di installazione di default di 0cRed Hat07 Linux usa il rilevamento 
automatico per riconoscere l'hardware del sistema. Sebbene la maggior parte
dei sistemi vengano riconosciuti senza problemi, in alcuni casi si possono
verificare dei problemi. Per evitarli, si consiglia di usare la 
modalit… expert. 

Per avviare l'installazione usando la modalit… expert, digitate 0fexpert <ENTER>07.

Una volta che sarete  nella modalit…, avrete un totale controllo sul processo
di installazione e potrete inoltre inserire i parametri opzionali dei moduli.









05[F1-Principale] [F2-Generale] [F3-Expert] [F4-Kernel] [F5-Rescue]07
