

                        09General Boot Help07

E' possibile attivare l'installazione di 0cRed Hat07 Linux , direttamente 
da questo prompt.  Nella maggior parte dei casi, si attiva il programma di
installazione premendo il tasto 0f<ENTER>07.

Alcune configurazioni hardware potrebbero creare qualche problema per il
riconoscimento automatico dell'hardware. Anche se e' raro, puo' comunque 
capitare.  Se avete qualche problema durante il processo di installazione,
riattivate il sistema usando l'expert mode.  Premete 05<F3>07 per avere 
piu' informazioni sulla modalita' expert.

Ci sono vari parametri che possono essere passati al kernel di Linux dal boot
del sistema.  Non e' possibile inserire i parametri per dispositivi come  
CD-ROM o schede di rete.  Premete 05<F5>07 per maggiori informazioni. 






05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07

