

                        09Modalita' rescue - Help07

Il CD-ROM 0cRed Hat07 Linux comprende la modalita' rescue che serve a ripristinare
un sistema che non si avvia in modo adeguato. La modalita' include molte 
utility (editor, tool RAID e tool per il disco fisso) che permettono di 
riportare il sistema a uno stato funzionante.

Per attivare la modalita' rescue, avviate il sistema dal CD-ROM 0cRed Hat07 Linux e digitate 0flinux rescue <ENTER>07.












05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07
