

                        09Rescue Mode Help07

Il CD-ROM di 0cRed Hat07 Linux offre la modalita' rescue per ripristinare
un sistema non funzionante. Tramite la modalita' rescue si possono utilizzare
varie utility (editor, tool per i dischi e per i sistemi RAID, ecc.) per
ripristinare un sistema danneggiato.

Per attivare la modalita' rescue, avviate il sistema dal CDROM di
0cRed Hat07 Linux e digitate 0flinux rescue <ENTER>07.












05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07

