00


                        01Kernel Parameter Help07

Some kernel parameters can be specified on the command line and will be
passed to the kernel.

To pass an option to the kernel, use the following format:

     01linux <options>07

If a different installation mode is desired, enter it after the option(s).

For example, to install on a system with 256MB of RAM using noprobe mode, 
type the following:

     01linux mem=256M noprobe07


0f[F1-Main] [F2-Options] [F3-General] [F4-Kernel] [F5-Rescue]07
