 
                09Welcome to 0cRed Hat09 Linux 7.0.91!07

 -  To install or upgrade 0cRed Hat07 Linux in graphical mode, 
    press the 0f<ENTER>07 key.

 -  To install or upgrade 0cRed Hat07 Linux in text mode, type: 0ftext <ENTER>07.

 -  To enable low resolution mode, type: 0flowres <ENTER>07.  
    Press 05<F2>07 for more information about low resolution mode.

 -  To disable framebuffer mode, type: 0fnofb <ENTER>07.  
    Press 05<F2>07 for more information about disabling framebuffer mode.

 -  To enable expert mode, type: 0fexpert <ENTER>07.  
    Press 05<F3>07 for more information about expert mode.

 -  To enable rescue mode, type: 0flinux rescue <ENTER>07.  
    Press 05<F5>07 for more information about rescue mode.

 -  If you have a driver disk, type: 0flinux dd <ENTER>07.

 -  Use the function keys listed below for more information.

05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07
