

                        09General Boot Help07

You can load the 0cRed Hat07 Linux installation program, and begin the 
installation process from this prompt.  In most cases, the best way to
get started is to simply press the 0f<ENTER>07 key.

Certain hardware configurations may have trouble with the automatic hardware
detection done during the installation.  While this is unusual, it does
happen occasionally.  If you experience problems during the installation,
restart the installation using expert mode.  Press 05<F3>07 for more
information on expert mode.

There are a number of parameters that can be passed to the Linux kernel
at boot time.  These do not include parameters for devices such as
CD-ROM drives or ethernet cards.  Press 05<F4>07 for more information. 






05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07
