#!/bin/bash
#
# rebuild_boot_iso
#
# This script is used to cleanly rebuild boot.iso from the current
# checked out branch.
#
# ask for sudo now, so we have it when we get to the image build

help() {
    cat <<EOF
This script will build the anaconda RPMs and then build boot.iso
from these.

Before starting the build it will remove all the previous build
artifacts.

Usage:
  Start the build process:
    $0 [options]

Options:
 -h, --help                         Print this help
EOF
}

# parse arguments
eval set -- "$(getopt -o h --long help -- "$@")"

while true; do
    case "${1:-}" in
        -h|--help) help; exit 0 ;;
        --) shift; break ;;
    esac
    shift
done


echo "warming up sudo!"
sudo true
BOOT_ISO="result/iso/boot.iso"
UPDATED_BOOT_ISO="result/iso/boot.iso.git_rev"
BOOT_ISO_GIT_REVISION="result/iso/boot.iso.git_rev"
# remove any previous package and relevant iso artifacts
rm -rf result/build/
rm -f ${BOOT_ISO}
rm -f ${UPDATED_BOOT_ISO}
rm -f ${BOOT_ISO_GIT_REVISION}
# make sure the iso folder actually exists
mkdir -p result/iso/
# note the Git revision from which we build the boot.iso
git rev-parse HEAD > result/iso/boot.iso.git_rev
make -f ./Makefile.am container-rpms-scratch
make -f ./Makefile.am anaconda-iso-creator-build
make -f ./Makefile.am container-iso-build
