#!/usr/bin/python3
#
# Copyright (C) 2021 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; If not, see <http://www.gnu.org/licenses/>.

import os
import sys

# import Cockpit's machinery for test VMs and its browser test API
TEST_DIR = os.path.dirname(__file__)
sys.path.append(os.path.join(TEST_DIR, "common"))
sys.path.append(os.path.join(os.path.dirname(TEST_DIR), "bots/machine"))

from testlib import MachineCase, nondestructive, test_main  # noqa


TIMEZONE_INTERFACE = "org.fedoraproject.Anaconda.Modules.Timezone"
TIMEZONE_OBJECT_PATH = "/org/fedoraproject/Anaconda/Modules/Timezone"


@nondestructive
class TestAnacondaWebUI(MachineCase):

    def testBasic(self):
        b = self.browser
        m = self.machine

        bus_address = m.execute("cat /run/anaconda/bus.address")
        get_ntp_enabled_cmd = (
            f'dbus-send --print-reply --bus="{bus_address}" \
              --dest={TIMEZONE_INTERFACE} \
              {TIMEZONE_OBJECT_PATH} \
              org.freedesktop.DBus.Properties.Get \
              string:"{TIMEZONE_INTERFACE}" string:"NTPEnabled"'
        )
        set_ntp_enabled_cmd = (
            lambda value: f'dbus-send --print-reply --bus="{bus_address}" \
              --dest={TIMEZONE_INTERFACE} \
              {TIMEZONE_OBJECT_PATH} \
              {TIMEZONE_INTERFACE}.SetNTPEnabled \
              boolean:"{value}"'
        )

        b.open("/cockpit/@localhost/anaconda-webui/index.html")
        b.wait_in_text(".pf-c-card__title", "Anaconda Web UI")

        # Read NTPEnabled property from the DBUS API
        # and make sure it matches the value displayed in the WebUI
        ntp_enabled = m.execute(get_ntp_enabled_cmd)
        self.assertIn("boolean true", ntp_enabled)
        b.wait_visible("#switch-ntp-enabled:checked")

        # Change NTPEnabled property from the WebUI
        # and make sure the change it reflected in the CLI
        b.click("#switch-ntp-enabled")
        b.wait_visible("#switch-ntp-enabled:not(checked)")
        ntp_enabled_new = m.execute(get_ntp_enabled_cmd)
        self.assertIn("boolean false", ntp_enabled_new)

        # Change NTPEnabled property from the CLI
        # and make sure the change is reflected in the WebUI
        m.execute(set_ntp_enabled_cmd("true"))
        b.wait_visible("#switch-ntp-enabled:checked")


if __name__ == '__main__':
    test_main()
