#!/usr/bin/python

import rpm
import os

fd = os.open('/mnt/redhat/comps/dist/6.1/i386/fileutils-4.0-2.i386.rpm', 0)
(h, isSource) = rpm.headerFromPackage(fd)

print "name", h[1000]
print "name", h['NAME']

for n in h.keys(): 
    print rpm.tagnames[n], h[n]
