name: cockpit-lib-update
on:
  # Runs every Thursday at 2 AM
  schedule:
    - cron: '0 2 * * 4'
  # can be run manually on https://github.com/rhinstaller/anaconda/actions
  workflow_dispatch:

jobs:
  cockpit-lib-update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y make

      - name: Set up configuration and secrets
        run: |
          printf '[user]\n\tname = github-actions\n\temail=github-actions@github.com\n' > ~/.gitconfig
          echo '${{ secrets.GITHUB_TOKEN }}' > ~/.config/github-token

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.INSTALLKER_TOKEN }}

      - name: Run cockpit-lib-update
        run: |
          make -f Makefile.am bots # HACK: to skip running autogen.sh/configure
          bots/cockpit-lib-update Makefile.am
        working-directory: ui/webui
