name: Run tests on push
on:
  push:
    branches:
      - master
      - f[0-9]+-devel
      - f[0-9]+-release

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Build anaconda-ci container
        run: make -f Makefile.am anaconda-ci-build

      - name: Run tests in anaconda-ci container
        run: |
          # put the log in the output, where it's easy to read and link to
          make -f Makefile.am container-ci || { cat test-logs/test-suite.log; exit 1; }

      - name: Upload test and coverage logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: 'logs'
          path: test-logs/*

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v2.0.2
